extern crate failure;

use std::collections::HashMap;

use std::fs::File;
use std::io::{BufReader, BufRead};

fn main() {
    run().unwrap();
}

fn run() -> Result<(), failure::Error> {

    let mut map = HashMap::new();

if *map.get("wnh").unwrap_or(&0) < -1 { let mut v = map.entry("o").or_insert(0); *v -= -427; }
if *map.get("baj").unwrap_or(&0) <= 3 { let mut v = map.entry("ugc").or_insert(0); *v -= -128; }
if *map.get("xml").unwrap_or(&0) <= -1 { let mut v = map.entry("ugc").or_insert(0); *v += 294; }
if *map.get("wfu").unwrap_or(&0) < -2 { let mut v = map.entry("ugc").or_insert(0); *v += -277; }
if *map.get("sqf").unwrap_or(&0) == 0 { let mut v = map.entry("l").or_insert(0); *v += 302; }
if *map.get("wnh").unwrap_or(&0) > -6 { let mut v = map.entry("l").or_insert(0); *v += -940; }
if *map.get("fy").unwrap_or(&0) >= -3 { let mut v = map.entry("vke").or_insert(0); *v += 687; }
if *map.get("ugc").unwrap_or(&0) > 118 { let mut v = map.entry("b").or_insert(0); *v += 976; }
if *map.get("jyi").unwrap_or(&0) < 5 { let mut v = map.entry("rz").or_insert(0); *v -= 201; }
if *map.get("l").unwrap_or(&0) >= -647 { let mut v = map.entry("y").or_insert(0); *v -= -960; }
if *map.get("xbp").unwrap_or(&0) <= 3 { let mut v = map.entry("baj").or_insert(0); *v -= 879; }
if *map.get("b").unwrap_or(&0) <= 981 { let mut v = map.entry("vke").or_insert(0); *v -= 360; }
if *map.get("baj").unwrap_or(&0) <= -875 { let mut v = map.entry("az").or_insert(0); *v -= 237; }
if *map.get("pp").unwrap_or(&0) > -7 { let mut v = map.entry("wnh").or_insert(0); *v -= 818; }
if *map.get("ugc").unwrap_or(&0) >= 121 { let mut v = map.entry("baj").or_insert(0); *v -= -434; }
if *map.get("k").unwrap_or(&0) < 1 { let mut v = map.entry("az").or_insert(0); *v += 501; }
if *map.get("sb").unwrap_or(&0) < 4 { let mut v = map.entry("y").or_insert(0); *v += 43; }
if *map.get("o").unwrap_or(&0) < 3 { let mut v = map.entry("e").or_insert(0); *v -= -195; }
if *map.get("u").unwrap_or(&0) == 0 { let mut v = map.entry("y").or_insert(0); *v += 729; }
if *map.get("xbp").unwrap_or(&0) <= 0 { let mut v = map.entry("l").or_insert(0); *v += 993; }
if *map.get("o").unwrap_or(&0) < 5 { let mut v = map.entry("u").or_insert(0); *v += -252; }
if *map.get("k").unwrap_or(&0) == 0 { let mut v = map.entry("k").or_insert(0); *v += 547; }
if *map.get("c").unwrap_or(&0) != 4 { let mut v = map.entry("e").or_insert(0); *v += -781; }
if *map.get("k").unwrap_or(&0) >= 545 { let mut v = map.entry("y").or_insert(0); *v += -963; }
if *map.get("xml").unwrap_or(&0) != -9 { let mut v = map.entry("k").or_insert(0); *v += -906; }
if *map.get("rz").unwrap_or(&0) <= -210 { let mut v = map.entry("k").or_insert(0); *v -= 394; }
if *map.get("baj").unwrap_or(&0) < -442 { let mut v = map.entry("l").or_insert(0); *v -= 676; }
if *map.get("sqf").unwrap_or(&0) >= -7 { let mut v = map.entry("rz").or_insert(0); *v += -376; }
if *map.get("sz").unwrap_or(&0) >= 6 { let mut v = map.entry("l").or_insert(0); *v += -388; }
if *map.get("jyi").unwrap_or(&0) < -1 { let mut v = map.entry("jyi").or_insert(0); *v -= 464; }
if *map.get("rz").unwrap_or(&0) == -577 { let mut v = map.entry("sb").or_insert(0); *v -= -397; }
if *map.get("b").unwrap_or(&0) != 975 { let mut v = map.entry("jyi").or_insert(0); *v -= -391; }
if *map.get("xbp").unwrap_or(&0) != 2 { let mut v = map.entry("rz").or_insert(0); *v -= 85; }
if *map.get("az").unwrap_or(&0) != 255 { let mut v = map.entry("rz").or_insert(0); *v -= -971; }
if *map.get("vke").unwrap_or(&0) < 337 { let mut v = map.entry("e").or_insert(0); *v += 622; }
if *map.get("l").unwrap_or(&0) < -318 { let mut v = map.entry("pp").or_insert(0); *v -= 506; }
if *map.get("az").unwrap_or(&0) < 262 { let mut v = map.entry("k").or_insert(0); *v += -471; }
if *map.get("vke").unwrap_or(&0) <= 331 { let mut v = map.entry("wnh").or_insert(0); *v -= -346; }
if *map.get("o").unwrap_or(&0) != 1 { let mut v = map.entry("sb").or_insert(0); *v -= 23; }
if *map.get("k").unwrap_or(&0) != -349 { let mut v = map.entry("y").or_insert(0); *v -= -29; }
if *map.get("sb").unwrap_or(&0) < 377 { let mut v = map.entry("fy").or_insert(0); *v += 83; }
if *map.get("tme").unwrap_or(&0) < 3 { let mut v = map.entry("c").or_insert(0); *v -= -283; }
if *map.get("e").unwrap_or(&0) == 34 { let mut v = map.entry("az").or_insert(0); *v -= 852; }
if *map.get("b").unwrap_or(&0) == 976 { let mut v = map.entry("fy").or_insert(0); *v += 935; }
if *map.get("e").unwrap_or(&0) <= 44 { let mut v = map.entry("pp").or_insert(0); *v -= 553; }
if *map.get("k").unwrap_or(&0) < -366 { let mut v = map.entry("sz").or_insert(0); *v -= 847; }
if *map.get("o").unwrap_or(&0) != -1 { let mut v = map.entry("wnh").or_insert(0); *v -= -717; }
if *map.get("e").unwrap_or(&0) == 26 { let mut v = map.entry("xbp").or_insert(0); *v -= -607; }
if *map.get("y").unwrap_or(&0) > 788 { let mut v = map.entry("jyi").or_insert(0); *v += -362; }
if *map.get("baj").unwrap_or(&0) <= -440 { let mut v = map.entry("wfu").or_insert(0); *v += 306; }
if *map.get("pp").unwrap_or(&0) == -1065 { let mut v = map.entry("sb").or_insert(0); *v += -512; }
if *map.get("sqf").unwrap_or(&0) != -4 { let mut v = map.entry("jyi").or_insert(0); *v -= -190; }
if *map.get("sqf").unwrap_or(&0) >= -6 { let mut v = map.entry("k").or_insert(0); *v -= 810; }
if *map.get("fy").unwrap_or(&0) > 1011 { let mut v = map.entry("u").or_insert(0); *v += 76; }
if *map.get("c").unwrap_or(&0) <= 286 { let mut v = map.entry("sqf").or_insert(0); *v += -844; }
if *map.get("k").unwrap_or(&0) <= -1162 { let mut v = map.entry("wnh").or_insert(0); *v += -326; }
if *map.get("baj").unwrap_or(&0) == -447 { let mut v = map.entry("wnh").or_insert(0); *v -= -199; }
if *map.get("sqf").unwrap_or(&0) < -839 { let mut v = map.entry("k").or_insert(0); *v += -828; }
if *map.get("l").unwrap_or(&0) > -321 { let mut v = map.entry("wnh").or_insert(0); *v += 288; }
if *map.get("c").unwrap_or(&0) != 280 { let mut v = map.entry("o").or_insert(0); *v -= 769; }
if *map.get("rz").unwrap_or(&0) > 299 { let mut v = map.entry("pp").or_insert(0); *v -= -95; }
if *map.get("b").unwrap_or(&0) <= 982 { let mut v = map.entry("vke").or_insert(0); *v -= -752; }
if *map.get("pp").unwrap_or(&0) == -964 { let mut v = map.entry("rz").or_insert(0); *v += 334; }
if *map.get("y").unwrap_or(&0) >= 797 { let mut v = map.entry("sqf").or_insert(0); *v += 987; }
if *map.get("az").unwrap_or(&0) > 271 { let mut v = map.entry("eia").or_insert(0); *v += -938; }
if *map.get("b").unwrap_or(&0) > 972 { let mut v = map.entry("tme").or_insert(0); *v -= 849; }
if *map.get("c").unwrap_or(&0) <= 282 { let mut v = map.entry("vke").or_insert(0); *v += 322; }
if *map.get("baj").unwrap_or(&0) >= -446 { let mut v = map.entry("l").or_insert(0); *v += -43; }
if *map.get("rz").unwrap_or(&0) <= 641 { let mut v = map.entry("fy").or_insert(0); *v -= 760; }
if *map.get("wnh").unwrap_or(&0) != -80 { let mut v = map.entry("sqf").or_insert(0); *v -= 947; }
if *map.get("eia").unwrap_or(&0) == -6 { let mut v = map.entry("e").or_insert(0); *v += 267; }
if *map.get("b").unwrap_or(&0) >= 975 { let mut v = map.entry("xbp").or_insert(0); *v -= -340; }
if *map.get("wfu").unwrap_or(&0) != 315 { let mut v = map.entry("xbp").or_insert(0); *v -= 887; }
if *map.get("o").unwrap_or(&0) < -766 { let mut v = map.entry("az").or_insert(0); *v += 911; }
if *map.get("wnh").unwrap_or(&0) < -87 { let mut v = map.entry("sb").or_insert(0); *v += 494; }
if *map.get("sz").unwrap_or(&0) <= 8 { let mut v = map.entry("sqf").or_insert(0); *v -= -25; }
if *map.get("xml").unwrap_or(&0) == 0 { let mut v = map.entry("fy").or_insert(0); *v -= -36; }
if *map.get("rz").unwrap_or(&0) >= 652 { let mut v = map.entry("ugc").or_insert(0); *v -= 429; }
if *map.get("ugc").unwrap_or(&0) <= 130 { let mut v = map.entry("sz").or_insert(0); *v -= 139; }
if *map.get("sz").unwrap_or(&0) != -141 { let mut v = map.entry("eia").or_insert(0); *v += -762; }
if *map.get("vke").unwrap_or(&0) == 1079 { let mut v = map.entry("c").or_insert(0); *v += 868; }
if *map.get("pp").unwrap_or(&0) > -974 { let mut v = map.entry("l").or_insert(0); *v -= 36; }
if *map.get("wnh").unwrap_or(&0) != -81 { let mut v = map.entry("jyi").or_insert(0); *v -= -645; }
if *map.get("tme").unwrap_or(&0) > -840 { let mut v = map.entry("tme").or_insert(0); *v += -361; }
if *map.get("eia").unwrap_or(&0) != -762 { let mut v = map.entry("sqf").or_insert(0); *v += 761; }
if *map.get("xbp").unwrap_or(&0) != -548 { let mut v = map.entry("o").or_insert(0); *v += 361; }
if *map.get("pp").unwrap_or(&0) > -969 { let mut v = map.entry("pp").or_insert(0); *v -= -999; }
if *map.get("k").unwrap_or(&0) <= -1995 { let mut v = map.entry("sz").or_insert(0); *v += -383; }
if *map.get("ugc").unwrap_or(&0) != 132 { let mut v = map.entry("y").or_insert(0); *v -= -940; }
if *map.get("k").unwrap_or(&0) < -1989 { let mut v = map.entry("sqf").or_insert(0); *v -= -957; }
if *map.get("e").unwrap_or(&0) >= 38 { let mut v = map.entry("tme").or_insert(0); *v -= 528; }
if *map.get("rz").unwrap_or(&0) == 643 { let mut v = map.entry("baj").or_insert(0); *v += -803; }
if *map.get("sz").unwrap_or(&0) > -530 { let mut v = map.entry("y").or_insert(0); *v += 799; }
if *map.get("vke").unwrap_or(&0) != 1086 { let mut v = map.entry("fy").or_insert(0); *v -= 120; }
if *map.get("pp").unwrap_or(&0) <= 36 { let mut v = map.entry("wnh").or_insert(0); *v += 141; }
if *map.get("wfu").unwrap_or(&0) == 306 { let mut v = map.entry("c").or_insert(0); *v -= 481; }
if *map.get("eia").unwrap_or(&0) < -758 { let mut v = map.entry("tme").or_insert(0); *v += 536; }
if *map.get("u").unwrap_or(&0) <= -174 { let mut v = map.entry("sz").or_insert(0); *v += 954; }
if *map.get("y").unwrap_or(&0) <= 2528 { let mut v = map.entry("o").or_insert(0); *v -= 473; }
if *map.get("wfu").unwrap_or(&0) >= 297 { let mut v = map.entry("l").or_insert(0); *v -= 976; }
if *map.get("baj").unwrap_or(&0) != -1252 { let mut v = map.entry("tme").or_insert(0); *v += -26; }
if *map.get("xml").unwrap_or(&0) > -7 { let mut v = map.entry("k").or_insert(0); *v -= 786; }
if *map.get("sqf").unwrap_or(&0) == 178 { let mut v = map.entry("az").or_insert(0); *v -= 817; }
if *map.get("k").unwrap_or(&0) == -2776 { let mut v = map.entry("c").or_insert(0); *v -= 980; }
if *map.get("tme").unwrap_or(&0) == -348 { let mut v = map.entry("baj").or_insert(0); *v -= -954; }
if *map.get("vke").unwrap_or(&0) <= 1088 { let mut v = map.entry("rz").or_insert(0); *v += -178; }
if *map.get("fy").unwrap_or(&0) >= 930 { let mut v = map.entry("jyi").or_insert(0); *v += 426; }
if *map.get("wnh").unwrap_or(&0) >= 63 { let mut v = map.entry("xbp").or_insert(0); *v += -708; }
if *map.get("az").unwrap_or(&0) > 353 { let mut v = map.entry("c").or_insert(0); *v += 364; }
if *map.get("xml").unwrap_or(&0) == 0 { let mut v = map.entry("l").or_insert(0); *v -= -393; }
if *map.get("l").unwrap_or(&0) != -983 { let mut v = map.entry("wfu").or_insert(0); *v -= -619; }
if *map.get("xbp").unwrap_or(&0) == -547 { let mut v = map.entry("y").or_insert(0); *v += -454; }
if *map.get("jyi").unwrap_or(&0) >= 642 { let mut v = map.entry("wnh").or_insert(0); *v += 909; }
if *map.get("k").unwrap_or(&0) > -2777 { let mut v = map.entry("az").or_insert(0); *v += 251; }
if *map.get("rz").unwrap_or(&0) >= 470 { let mut v = map.entry("c").or_insert(0); *v += 985; }
if *map.get("wnh").unwrap_or(&0) <= 978 { let mut v = map.entry("e").or_insert(0); *v += -810; }
if *map.get("fy").unwrap_or(&0) == 934 { let mut v = map.entry("e").or_insert(0); *v += 785; }
if *map.get("vke").unwrap_or(&0) >= 1083 { let mut v = map.entry("wnh").or_insert(0); *v -= -872; }
if *map.get("rz").unwrap_or(&0) > 457 { let mut v = map.entry("baj").or_insert(0); *v -= -827; }
if *map.get("sqf").unwrap_or(&0) > 170 { let mut v = map.entry("wfu").or_insert(0); *v -= -186; }
if *map.get("wnh").unwrap_or(&0) > 970 { let mut v = map.entry("sqf").or_insert(0); *v += 522; }
if *map.get("wfu").unwrap_or(&0) <= 489 { let mut v = map.entry("sb").or_insert(0); *v += 307; }
if *map.get("sz").unwrap_or(&0) == 432 { let mut v = map.entry("ugc").or_insert(0); *v -= -765; }
if *map.get("e").unwrap_or(&0) > 7 { let mut v = map.entry("wfu").or_insert(0); *v += 429; }
if *map.get("jyi").unwrap_or(&0) <= 653 { let mut v = map.entry("fy").or_insert(0); *v += 730; }
if *map.get("sb").unwrap_or(&0) >= 376 { let mut v = map.entry("sb").or_insert(0); *v -= -265; }
if *map.get("c").unwrap_or(&0) == 1033 { let mut v = map.entry("b").or_insert(0); *v -= -276; }
if *map.get("k").unwrap_or(&0) > -2788 { let mut v = map.entry("u").or_insert(0); *v += -99; }
if *map.get("l").unwrap_or(&0) >= -986 { let mut v = map.entry("e").or_insert(0); *v += 114; }
if *map.get("wnh").unwrap_or(&0) >= 963 { let mut v = map.entry("vke").or_insert(0); *v -= -845; }
if *map.get("xbp").unwrap_or(&0) > -549 { let mut v = map.entry("c").or_insert(0); *v += -263; }
if *map.get("sz").unwrap_or(&0) > 425 { let mut v = map.entry("sz").or_insert(0); *v += 905; }
if *map.get("o").unwrap_or(&0) >= -412 { let mut v = map.entry("baj").or_insert(0); *v -= 298; }
if *map.get("baj").unwrap_or(&0) == -719 { let mut v = map.entry("l").or_insert(0); *v -= 118; }
if *map.get("pp").unwrap_or(&0) >= 31 { let mut v = map.entry("rz").or_insert(0); *v += -472; }
if *map.get("fy").unwrap_or(&0) <= 1670 { let mut v = map.entry("sb").or_insert(0); *v -= 489; }
if *map.get("sqf").unwrap_or(&0) == 178 { let mut v = map.entry("xbp").or_insert(0); *v -= 876; }
if *map.get("o").unwrap_or(&0) != -407 { let mut v = map.entry("y").or_insert(0); *v -= 504; }
if *map.get("xbp").unwrap_or(&0) >= -1427 { let mut v = map.entry("u").or_insert(0); *v += 410; }
if *map.get("xml").unwrap_or(&0) != -2 { let mut v = map.entry("xml").or_insert(0); *v -= 95; }
if *map.get("xml").unwrap_or(&0) <= -101 { let mut v = map.entry("wfu").or_insert(0); *v -= 440; }
if *map.get("pp").unwrap_or(&0) <= 39 { let mut v = map.entry("sqf").or_insert(0); *v -= -270; }
if *map.get("pp").unwrap_or(&0) >= 34 { let mut v = map.entry("k").or_insert(0); *v += -812; }
if *map.get("pp").unwrap_or(&0) > 27 { let mut v = map.entry("jyi").or_insert(0); *v -= -498; }
if *map.get("vke").unwrap_or(&0) != 1924 { let mut v = map.entry("jyi").or_insert(0); *v -= 848; }
if *map.get("sqf").unwrap_or(&0) > 440 { let mut v = map.entry("xbp").or_insert(0); *v += 675; }
if *map.get("b").unwrap_or(&0) <= 981 { let mut v = map.entry("jyi").or_insert(0); *v -= -697; }
if *map.get("baj").unwrap_or(&0) > -725 { let mut v = map.entry("jyi").or_insert(0); *v -= 172; }
if *map.get("c").unwrap_or(&0) >= 767 { let mut v = map.entry("fy").or_insert(0); *v += 349; }
if *map.get("c").unwrap_or(&0) >= 771 { let mut v = map.entry("wnh").or_insert(0); *v += -683; }
if *map.get("u").unwrap_or(&0) <= 144 { let mut v = map.entry("e").or_insert(0); *v += -667; }
if *map.get("rz").unwrap_or(&0) != -7 { let mut v = map.entry("jyi").or_insert(0); *v -= -991; }
if *map.get("k").unwrap_or(&0) < -3586 { let mut v = map.entry("sb").or_insert(0); *v += 547; }
if *map.get("jyi").unwrap_or(&0) != 1669 { let mut v = map.entry("l").or_insert(0); *v += -645; }
if *map.get("xml").unwrap_or(&0) > -99 { let mut v = map.entry("sqf").or_insert(0); *v -= 912; }
if *map.get("az").unwrap_or(&0) >= 354 { let mut v = map.entry("u").or_insert(0); *v += 782; }
if *map.get("xbp").unwrap_or(&0) > -755 { let mut v = map.entry("az").or_insert(0); *v -= 752; }
if *map.get("k").unwrap_or(&0) >= -3603 { let mut v = map.entry("y").or_insert(0); *v -= 296; }
if *map.get("fy").unwrap_or(&0) >= 2007 { let mut v = map.entry("c").or_insert(0); *v -= -816; }
if *map.get("pp").unwrap_or(&0) < 43 { let mut v = map.entry("sqf").or_insert(0); *v += 776; }
if *map.get("l").unwrap_or(&0) != -1742 { let mut v = map.entry("wfu").or_insert(0); *v += 502; }
if *map.get("e").unwrap_or(&0) != -542 { let mut v = map.entry("sb").or_insert(0); *v -= 228; }
if *map.get("k").unwrap_or(&0) == -3595 { let mut v = map.entry("fy").or_insert(0); *v += 171; }
if *map.get("jyi").unwrap_or(&0) < 1663 { let mut v = map.entry("wnh").or_insert(0); *v -= 998; }
if *map.get("xbp").unwrap_or(&0) == -748 { let mut v = map.entry("k").or_insert(0); *v -= -762; }
if *map.get("az").unwrap_or(&0) == -394 { let mut v = map.entry("tme").or_insert(0); *v -= -660; }
if *map.get("vke").unwrap_or(&0) == 1924 { let mut v = map.entry("eia").or_insert(0); *v += 969; }
if *map.get("sqf").unwrap_or(&0) != 309 { let mut v = map.entry("l").or_insert(0); *v += -324; }
if *map.get("sz").unwrap_or(&0) >= 1336 { let mut v = map.entry("az").or_insert(0); *v += -982; }
if *map.get("tme").unwrap_or(&0) == 321 { let mut v = map.entry("rz").or_insert(0); *v -= 651; }
if *map.get("vke").unwrap_or(&0) == 1924 { let mut v = map.entry("xbp").or_insert(0); *v -= -196; }
if *map.get("b").unwrap_or(&0) > 973 { let mut v = map.entry("eia").or_insert(0); *v += 538; }
if *map.get("k").unwrap_or(&0) >= -2842 { let mut v = map.entry("eia").or_insert(0); *v += -326; }
if *map.get("eia").unwrap_or(&0) <= 422 { let mut v = map.entry("baj").or_insert(0); *v -= -47; }
if *map.get("eia").unwrap_or(&0) == 419 { let mut v = map.entry("jyi").or_insert(0); *v += -851; }
if *map.get("xbp").unwrap_or(&0) >= -553 { let mut v = map.entry("ugc").or_insert(0); *v -= -846; }
if *map.get("wfu").unwrap_or(&0) < 1424 { let mut v = map.entry("e").or_insert(0); *v += -473; }
if *map.get("k").unwrap_or(&0) < -2832 { let mut v = map.entry("sqf").or_insert(0); *v += -401; }
if *map.get("c").unwrap_or(&0) > 1591 { let mut v = map.entry("c").or_insert(0); *v += 975; }
if *map.get("xbp").unwrap_or(&0) == -552 { let mut v = map.entry("o").or_insert(0); *v += -235; }
if *map.get("k").unwrap_or(&0) < -2827 { let mut v = map.entry("xml").or_insert(0); *v -= -34; }
if *map.get("e").unwrap_or(&0) >= -1016 { let mut v = map.entry("xbp").or_insert(0); *v += 333; }
if *map.get("sz").unwrap_or(&0) > 1327 { let mut v = map.entry("baj").or_insert(0); *v -= -74; }
if *map.get("vke").unwrap_or(&0) >= 1921 { let mut v = map.entry("xml").or_insert(0); *v -= -288; }
if *map.get("pp").unwrap_or(&0) <= 42 { let mut v = map.entry("sqf").or_insert(0); *v += -180; }
if *map.get("b").unwrap_or(&0) != 971 { let mut v = map.entry("wfu").or_insert(0); *v -= 820; }
if *map.get("vke").unwrap_or(&0) <= 1923 { let mut v = map.entry("e").or_insert(0); *v += -113; }
if *map.get("rz").unwrap_or(&0) > -661 { let mut v = map.entry("jyi").or_insert(0); *v += 466; }
if *map.get("pp").unwrap_or(&0) != 44 { let mut v = map.entry("eia").or_insert(0); *v += -410; }
if *map.get("l").unwrap_or(&0) > -2078 { let mut v = map.entry("az").or_insert(0); *v -= -404; }
if *map.get("az").unwrap_or(&0) < -979 { let mut v = map.entry("wfu").or_insert(0); *v += -537; }
if *map.get("pp").unwrap_or(&0) != 37 { let mut v = map.entry("xbp").or_insert(0); *v += -667; }
if *map.get("b").unwrap_or(&0) == 979 { let mut v = map.entry("sz").or_insert(0); *v += -774; }
if *map.get("b").unwrap_or(&0) >= 979 { let mut v = map.entry("sz").or_insert(0); *v -= 35; }
if *map.get("e").unwrap_or(&0) < -1020 { let mut v = map.entry("b").or_insert(0); *v += -641; }
if *map.get("c").unwrap_or(&0) <= 1588 { let mut v = map.entry("eia").or_insert(0); *v -= 914; }
if *map.get("o").unwrap_or(&0) > -647 { let mut v = map.entry("pp").or_insert(0); *v += -250; }
if *map.get("k").unwrap_or(&0) < -2830 { let mut v = map.entry("b").or_insert(0); *v -= 46; }
if *map.get("c").unwrap_or(&0) < 1589 { let mut v = map.entry("u").or_insert(0); *v += 275; }
if *map.get("az").unwrap_or(&0) < -971 { let mut v = map.entry("rz").or_insert(0); *v -= -946; }
if *map.get("sz").unwrap_or(&0) == 1337 { let mut v = map.entry("sqf").or_insert(0); *v += -197; }
if *map.get("tme").unwrap_or(&0) >= 321 { let mut v = map.entry("sqf").or_insert(0); *v -= -853; }
if *map.get("b").unwrap_or(&0) >= 923 { let mut v = map.entry("b").or_insert(0); *v -= -719; }
if *map.get("e").unwrap_or(&0) == -1015 { let mut v = map.entry("baj").or_insert(0); *v -= 614; }
if *map.get("u").unwrap_or(&0) < 1195 { let mut v = map.entry("o").or_insert(0); *v += -224; }
if *map.get("vke").unwrap_or(&0) <= 1925 { let mut v = map.entry("sqf").or_insert(0); *v -= 130; }
if *map.get("xml").unwrap_or(&0) >= 224 { let mut v = map.entry("eia").or_insert(0); *v += 388; }
if *map.get("pp").unwrap_or(&0) > -218 { let mut v = map.entry("xbp").or_insert(0); *v -= 561; }
if *map.get("k").unwrap_or(&0) >= -2841 { let mut v = map.entry("o").or_insert(0); *v -= -959; }
if *map.get("az").unwrap_or(&0) >= -972 { let mut v = map.entry("tme").or_insert(0); *v += -89; }
if *map.get("b").unwrap_or(&0) >= 1652 { let mut v = map.entry("xml").or_insert(0); *v -= 745; }
if *map.get("xml").unwrap_or(&0) <= 235 { let mut v = map.entry("baj").or_insert(0); *v -= 649; }
if *map.get("o").unwrap_or(&0) <= 101 { let mut v = map.entry("wfu").or_insert(0); *v += -762; }
if *map.get("jyi").unwrap_or(&0) >= 1277 { let mut v = map.entry("l").or_insert(0); *v += 424; }
if *map.get("o").unwrap_or(&0) == 101 { let mut v = map.entry("rz").or_insert(0); *v -= 685; }
if *map.get("baj").unwrap_or(&0) >= -1868 { let mut v = map.entry("u").or_insert(0); *v -= -49; }
if *map.get("eia").unwrap_or(&0) >= -517 { let mut v = map.entry("u").or_insert(0); *v -= -495; }
if *map.get("y").unwrap_or(&0) > 1273 { let mut v = map.entry("az").or_insert(0); *v += -450; }
if *map.get("y").unwrap_or(&0) == 1283 { let mut v = map.entry("sz").or_insert(0); *v -= -860; }
if *map.get("xml").unwrap_or(&0) >= 226 { let mut v = map.entry("wnh").or_insert(0); *v += -896; }
if *map.get("tme").unwrap_or(&0) >= 229 { let mut v = map.entry("eia").or_insert(0); *v -= -319; }
if *map.get("o").unwrap_or(&0) == 92 { let mut v = map.entry("vke").or_insert(0); *v += -535; }
if *map.get("fy").unwrap_or(&0) > 2190 { let mut v = map.entry("vke").or_insert(0); *v -= 10; }
if *map.get("l").unwrap_or(&0) == -1646 { let mut v = map.entry("b").or_insert(0); *v -= -683; }
if *map.get("jyi").unwrap_or(&0) > 1274 { let mut v = map.entry("tme").or_insert(0); *v -= -522; }
if *map.get("wnh").unwrap_or(&0) < -604 { let mut v = map.entry("tme").or_insert(0); *v += -211; }
if *map.get("rz").unwrap_or(&0) <= 285 { let mut v = map.entry("u").or_insert(0); *v -= -383; }
if *map.get("u").unwrap_or(&0) >= 1732 { let mut v = map.entry("baj").or_insert(0); *v += 928; }
if *map.get("y").unwrap_or(&0) <= 1282 { let mut v = map.entry("eia").or_insert(0); *v += -286; }
if *map.get("ugc").unwrap_or(&0) <= 1747 { let mut v = map.entry("pp").or_insert(0); *v -= -422; }
if *map.get("o").unwrap_or(&0) != 96 { let mut v = map.entry("e").or_insert(0); *v -= -123; }
if *map.get("wfu").unwrap_or(&0) == -159 { let mut v = map.entry("u").or_insert(0); *v -= -163; }
if *map.get("rz").unwrap_or(&0) <= 289 { let mut v = map.entry("y").or_insert(0); *v -= 802; }
if *map.get("eia").unwrap_or(&0) >= -199 { let mut v = map.entry("o").or_insert(0); *v -= -992; }
if *map.get("e").unwrap_or(&0) < -887 { let mut v = map.entry("sqf").or_insert(0); *v -= 275; }
if *map.get("e").unwrap_or(&0) < -889 { let mut v = map.entry("az").or_insert(0); *v += 801; }
if *map.get("c").unwrap_or(&0) < 1595 { let mut v = map.entry("pp").or_insert(0); *v += 893; }
if *map.get("o").unwrap_or(&0) < 1094 { let mut v = map.entry("sz").or_insert(0); *v += 913; }
if *map.get("k").unwrap_or(&0) <= -2833 { let mut v = map.entry("wfu").or_insert(0); *v += 870; }
if *map.get("wnh").unwrap_or(&0) < -609 { let mut v = map.entry("tme").or_insert(0); *v += -203; }
if *map.get("xml").unwrap_or(&0) < 228 { let mut v = map.entry("eia").or_insert(0); *v -= 431; }
if *map.get("sz").unwrap_or(&0) == 3110 { let mut v = map.entry("sqf").or_insert(0); *v -= -722; }
if *map.get("fy").unwrap_or(&0) > 2175 { let mut v = map.entry("xml").or_insert(0); *v += -527; }
if *map.get("fy").unwrap_or(&0) < 2176 { let mut v = map.entry("sqf").or_insert(0); *v -= -314; }
if *map.get("l").unwrap_or(&0) < -1636 { let mut v = map.entry("baj").or_insert(0); *v += -425; }
if *map.get("k").unwrap_or(&0) >= -2838 { let mut v = map.entry("rz").or_insert(0); *v -= -774; }
if *map.get("pp").unwrap_or(&0) != 1097 { let mut v = map.entry("jyi").or_insert(0); *v += -797; }
if *map.get("o").unwrap_or(&0) < 1091 { let mut v = map.entry("u").or_insert(0); *v += 856; }
if *map.get("o").unwrap_or(&0) > 1089 { let mut v = map.entry("ugc").or_insert(0); *v -= 29; }
if *map.get("rz").unwrap_or(&0) <= 1070 { let mut v = map.entry("wnh").or_insert(0); *v -= 629; }
if *map.get("fy").unwrap_or(&0) != 2184 { let mut v = map.entry("rz").or_insert(0); *v -= 919; }
if *map.get("fy").unwrap_or(&0) >= 2178 { let mut v = map.entry("wfu").or_insert(0); *v -= -789; }
if *map.get("wfu").unwrap_or(&0) < 1491 { let mut v = map.entry("o").or_insert(0); *v += 229; }
if *map.get("sb").unwrap_or(&0) != 432 { let mut v = map.entry("wnh").or_insert(0); *v += -873; }
if *map.get("rz").unwrap_or(&0) != 1062 { let mut v = map.entry("wfu").or_insert(0); *v += -29; }
if *map.get("ugc").unwrap_or(&0) == 1739 { let mut v = map.entry("pp").or_insert(0); *v -= 542; }
if *map.get("l").unwrap_or(&0) <= -1638 { let mut v = map.entry("tme").or_insert(0); *v -= -321; }
if *map.get("b").unwrap_or(&0) < 2340 { let mut v = map.entry("baj").or_insert(0); *v -= 515; }
if *map.get("sqf").unwrap_or(&0) >= 701 { let mut v = map.entry("k").or_insert(0); *v -= 976; }
if *map.get("eia").unwrap_or(&0) >= -631 { let mut v = map.entry("e").or_insert(0); *v -= -940; }
if *map.get("l").unwrap_or(&0) <= -1644 { let mut v = map.entry("b").or_insert(0); *v += 173; }
if *map.get("sb").unwrap_or(&0) < 439 { let mut v = map.entry("e").or_insert(0); *v += 649; }
if *map.get("c").unwrap_or(&0) > 1579 { let mut v = map.entry("ugc").or_insert(0); *v += 598; }
if *map.get("u").unwrap_or(&0) == 2755 { let mut v = map.entry("baj").or_insert(0); *v -= 920; }
if *map.get("eia").unwrap_or(&0) < -622 { let mut v = map.entry("sz").or_insert(0); *v += 165; }
if *map.get("fy").unwrap_or(&0) != 2181 { let mut v = map.entry("c").or_insert(0); *v += -461; }
if *map.get("pp").unwrap_or(&0) == 558 { let mut v = map.entry("sqf").or_insert(0); *v -= -574; }
if *map.get("o").unwrap_or(&0) <= 1089 { let mut v = map.entry("jyi").or_insert(0); *v += -511; }
if *map.get("pp").unwrap_or(&0) == 558 { let mut v = map.entry("k").or_insert(0); *v -= -876; }
if *map.get("wnh").unwrap_or(&0) < -1234 { let mut v = map.entry("l").or_insert(0); *v -= -830; }
if *map.get("pp").unwrap_or(&0) < 550 { let mut v = map.entry("az").or_insert(0); *v += -524; }
if *map.get("vke").unwrap_or(&0) < 1383 { let mut v = map.entry("y").or_insert(0); *v += 141; }
if *map.get("rz").unwrap_or(&0) <= 1067 { let mut v = map.entry("tme").or_insert(0); *v += 365; }
if *map.get("e").unwrap_or(&0) >= 696 { let mut v = map.entry("u").or_insert(0); *v += 33; }
if *map.get("sz").unwrap_or(&0) == 3275 { let mut v = map.entry("sqf").or_insert(0); *v += -241; }
if *map.get("baj").unwrap_or(&0) == -2793 { let mut v = map.entry("k").or_insert(0); *v -= 918; }
if *map.get("y").unwrap_or(&0) > 471 { let mut v = map.entry("jyi").or_insert(0); *v += 82; }
if *map.get("k").unwrap_or(&0) >= -3857 { let mut v = map.entry("sb").or_insert(0); *v -= 730; }
if *map.get("wnh").unwrap_or(&0) <= -1237 { let mut v = map.entry("u").or_insert(0); *v -= -690; }
if *map.get("e").unwrap_or(&0) >= 695 { let mut v = map.entry("jyi").or_insert(0); *v -= 962; }
if *map.get("wnh").unwrap_or(&0) <= -1238 { let mut v = map.entry("xml").or_insert(0); *v -= -513; }
if *map.get("sz").unwrap_or(&0) >= 3285 { let mut v = map.entry("sqf").or_insert(0); *v += -77; }
if *map.get("az").unwrap_or(&0) > -624 { let mut v = map.entry("wfu").or_insert(0); *v += 697; }
if *map.get("eia").unwrap_or(&0) < -621 { let mut v = map.entry("l").or_insert(0); *v -= 200; }
if *map.get("k").unwrap_or(&0) < -3846 { let mut v = map.entry("l").or_insert(0); *v += 258; }
if *map.get("b").unwrap_or(&0) <= 2513 { let mut v = map.entry("wnh").or_insert(0); *v -= -578; }
if *map.get("wnh").unwrap_or(&0) < -659 { let mut v = map.entry("l").or_insert(0); *v += -871; }
if *map.get("b").unwrap_or(&0) < 2496 { let mut v = map.entry("pp").or_insert(0); *v -= 916; }
if *map.get("fy").unwrap_or(&0) <= 2189 { let mut v = map.entry("eia").or_insert(0); *v += -445; }
if *map.get("o").unwrap_or(&0) >= 1077 { let mut v = map.entry("b").or_insert(0); *v -= -759; }
if *map.get("xml").unwrap_or(&0) != 219 { let mut v = map.entry("ugc").or_insert(0); *v += -582; }
if *map.get("sz").unwrap_or(&0) < 3280 { let mut v = map.entry("vke").or_insert(0); *v -= 915; }
if *map.get("sz").unwrap_or(&0) != 3271 { let mut v = map.entry("e").or_insert(0); *v -= 752; }
if *map.get("pp").unwrap_or(&0) > 550 { let mut v = map.entry("k").or_insert(0); *v += 447; }
if *map.get("jyi").unwrap_or(&0) > -910 { let mut v = map.entry("wnh").or_insert(0); *v += -272; }
if *map.get("xml").unwrap_or(&0) >= 209 { let mut v = map.entry("b").or_insert(0); *v += 762; }
if *map.get("eia").unwrap_or(&0) < -1070 { let mut v = map.entry("vke").or_insert(0); *v += 33; }
if *map.get("vke").unwrap_or(&0) >= 501 { let mut v = map.entry("wnh").or_insert(0); *v -= -943; }
if *map.get("wnh").unwrap_or(&0) != 4 { let mut v = map.entry("y").or_insert(0); *v -= -627; }
if *map.get("eia").unwrap_or(&0) >= -1080 { let mut v = map.entry("k").or_insert(0); *v -= -240; }
if *map.get("eia").unwrap_or(&0) <= -1069 { let mut v = map.entry("tme").or_insert(0); *v += -731; }
if *map.get("pp").unwrap_or(&0) < 567 { let mut v = map.entry("y").or_insert(0); *v += 138; }
if *map.get("u").unwrap_or(&0) < 3480 { let mut v = map.entry("wfu").or_insert(0); *v -= -839; }
if *map.get("az").unwrap_or(&0) >= -624 { let mut v = map.entry("sz").or_insert(0); *v -= -268; }
if *map.get("l").unwrap_or(&0) > -1629 { let mut v = map.entry("tme").or_insert(0); *v += 413; }
if *map.get("l").unwrap_or(&0) == -1626 { let mut v = map.entry("vke").or_insert(0); *v += 699; }
if *map.get("fy").unwrap_or(&0) != 2179 { let mut v = map.entry("pp").or_insert(0); *v -= 962; }
if *map.get("eia").unwrap_or(&0) != -1068 { let mut v = map.entry("pp").or_insert(0); *v += -972; }
if *map.get("xbp").unwrap_or(&0) < -1445 { let mut v = map.entry("e").or_insert(0); *v -= -223; }
if *map.get("xbp").unwrap_or(&0) > -1440 { let mut v = map.entry("pp").or_insert(0); *v += -559; }
if *map.get("sb").unwrap_or(&0) <= -299 { let mut v = map.entry("pp").or_insert(0); *v += -869; }
if *map.get("sz").unwrap_or(&0) == 3543 { let mut v = map.entry("wfu").or_insert(0); *v -= 229; }
if *map.get("fy").unwrap_or(&0) != 2189 { let mut v = map.entry("az").or_insert(0); *v -= -885; }
if *map.get("wfu").unwrap_or(&0) >= 2806 { let mut v = map.entry("tme").or_insert(0); *v += -542; }
if *map.get("e").unwrap_or(&0) >= 172 { let mut v = map.entry("sqf").or_insert(0); *v -= -797; }
if *map.get("c").unwrap_or(&0) >= 1119 { let mut v = map.entry("l").or_insert(0); *v += -159; }
if *map.get("e").unwrap_or(&0) > 158 { let mut v = map.entry("baj").or_insert(0); *v -= 602; }
if *map.get("sb").unwrap_or(&0) < -295 { let mut v = map.entry("sb").or_insert(0); *v -= -546; }
if *map.get("k").unwrap_or(&0) != -3171 { let mut v = map.entry("ugc").or_insert(0); *v += -531; }
if *map.get("sqf").unwrap_or(&0) > 1033 { let mut v = map.entry("xbp").or_insert(0); *v += -800; }
if *map.get("tme").unwrap_or(&0) >= -255 { let mut v = map.entry("eia").or_insert(0); *v -= 281; }
if *map.get("tme").unwrap_or(&0) != -247 { let mut v = map.entry("b").or_insert(0); *v += -997; }
if *map.get("xml").unwrap_or(&0) >= 216 { let mut v = map.entry("k").or_insert(0); *v += 140; }
if *map.get("pp").unwrap_or(&0) > -1377 { let mut v = map.entry("pp").or_insert(0); *v += -83; }
if *map.get("l").unwrap_or(&0) <= -1781 { let mut v = map.entry("sb").or_insert(0); *v += -697; }
if *map.get("wnh").unwrap_or(&0) < 19 { let mut v = map.entry("baj").or_insert(0); *v += 101; }
if *map.get("wnh").unwrap_or(&0) < 17 { let mut v = map.entry("b").or_insert(0); *v += -330; }
if *map.get("ugc").unwrap_or(&0) > 1219 { let mut v = map.entry("baj").or_insert(0); *v -= -602; }
if *map.get("tme").unwrap_or(&0) == -247 { let mut v = map.entry("fy").or_insert(0); *v -= 642; }
if *map.get("c").unwrap_or(&0) >= 1120 { let mut v = map.entry("e").or_insert(0); *v += 212; }
if *map.get("c").unwrap_or(&0) > 1122 { let mut v = map.entry("sqf").or_insert(0); *v -= 693; }
if *map.get("az").unwrap_or(&0) <= 265 { let mut v = map.entry("tme").or_insert(0); *v -= 277; }
if *map.get("ugc").unwrap_or(&0) >= 1222 { let mut v = map.entry("k").or_insert(0); *v -= 430; }
if *map.get("wfu").unwrap_or(&0) >= 2806 { let mut v = map.entry("rz").or_insert(0); *v += 182; }
if *map.get("wfu").unwrap_or(&0) == 2807 { let mut v = map.entry("sb").or_insert(0); *v += 158; }
if *map.get("wfu").unwrap_or(&0) == 2807 { let mut v = map.entry("wfu").or_insert(0); *v += -223; }
if *map.get("ugc").unwrap_or(&0) != 1224 { let mut v = map.entry("pp").or_insert(0); *v -= -734; }
if *map.get("c").unwrap_or(&0) != 1124 { let mut v = map.entry("rz").or_insert(0); *v -= -809; }
if *map.get("y").unwrap_or(&0) < 1247 { let mut v = map.entry("vke").or_insert(0); *v -= -963; }
if *map.get("l").unwrap_or(&0) != -1791 { let mut v = map.entry("sqf").or_insert(0); *v -= -654; }
if *map.get("o").unwrap_or(&0) < 1090 { let mut v = map.entry("az").or_insert(0); *v -= -939; }
if *map.get("vke").unwrap_or(&0) == 1470 { let mut v = map.entry("eia").or_insert(0); *v += 753; }
if *map.get("u").unwrap_or(&0) > 3473 { let mut v = map.entry("fy").or_insert(0); *v -= 494; }
if *map.get("ugc").unwrap_or(&0) > 1217 { let mut v = map.entry("jyi").or_insert(0); *v += -739; }
if *map.get("e").unwrap_or(&0) != 380 { let mut v = map.entry("jyi").or_insert(0); *v += 216; }
if *map.get("ugc").unwrap_or(&0) > 1222 { let mut v = map.entry("l").or_insert(0); *v += -95; }
if *map.get("baj").unwrap_or(&0) > -2695 { let mut v = map.entry("pp").or_insert(0); *v -= 400; }
if *map.get("k").unwrap_or(&0) < -3603 { let mut v = map.entry("o").or_insert(0); *v -= -915; }
if *map.get("c").unwrap_or(&0) <= 1128 { let mut v = map.entry("c").or_insert(0); *v -= 810; }
if *map.get("k").unwrap_or(&0) >= -3598 { let mut v = map.entry("fy").or_insert(0); *v -= 33; }
if *map.get("sz").unwrap_or(&0) <= 3540 { let mut v = map.entry("c").or_insert(0); *v += -193; }
if *map.get("l").unwrap_or(&0) > -1885 { let mut v = map.entry("ugc").or_insert(0); *v += -415; }
if *map.get("baj").unwrap_or(&0) != -2692 { let mut v = map.entry("c").or_insert(0); *v += 12; }
if *map.get("c").unwrap_or(&0) != 309 { let mut v = map.entry("eia").or_insert(0); *v -= 376; }
if *map.get("xbp").unwrap_or(&0) != -2255 { let mut v = map.entry("jyi").or_insert(0); *v += 168; }
if *map.get("sz").unwrap_or(&0) != 3553 { let mut v = map.entry("u").or_insert(0); *v -= 814; }
if *map.get("xbp").unwrap_or(&0) != -2247 { let mut v = map.entry("wfu").or_insert(0); *v -= 247; }
if *map.get("eia").unwrap_or(&0) <= -970 { let mut v = map.entry("xml").or_insert(0); *v -= -716; }
if *map.get("baj").unwrap_or(&0) <= -2689 { let mut v = map.entry("sqf").or_insert(0); *v -= -985; }
if *map.get("pp").unwrap_or(&0) != -1867 { let mut v = map.entry("sz").or_insert(0); *v += 280; }
if *map.get("jyi").unwrap_or(&0) <= -1475 { let mut v = map.entry("tme").or_insert(0); *v -= 277; }
if *map.get("l").unwrap_or(&0) == -1883 { let mut v = map.entry("pp").or_insert(0); *v -= 122; }
if *map.get("sz").unwrap_or(&0) != 3818 { let mut v = map.entry("tme").or_insert(0); *v -= -329; }
if *map.get("sb").unwrap_or(&0) == -291 { let mut v = map.entry("eia").or_insert(0); *v -= 980; }
if *map.get("b").unwrap_or(&0) > 3696 { let mut v = map.entry("jyi").or_insert(0); *v += 373; }
if *map.get("baj").unwrap_or(&0) < -2688 { let mut v = map.entry("y").or_insert(0); *v += -203; }
if *map.get("u").unwrap_or(&0) == 2664 { let mut v = map.entry("ugc").or_insert(0); *v += 263; }
if *map.get("xbp").unwrap_or(&0) >= -2250 { let mut v = map.entry("eia").or_insert(0); *v += -278; }
if *map.get("xbp").unwrap_or(&0) <= -2246 { let mut v = map.entry("ugc").or_insert(0); *v -= 654; }
if *map.get("rz").unwrap_or(&0) == 2053 { let mut v = map.entry("fy").or_insert(0); *v += 814; }
if *map.get("y").unwrap_or(&0) != 1034 { let mut v = map.entry("wnh").or_insert(0); *v += 709; }
if *map.get("tme").unwrap_or(&0) > -476 { let mut v = map.entry("e").or_insert(0); *v -= 939; }
if *map.get("az").unwrap_or(&0) > 1193 { let mut v = map.entry("wfu").or_insert(0); *v += -792; }
if *map.get("baj").unwrap_or(&0) <= -2689 { let mut v = map.entry("u").or_insert(0); *v += -506; }
if *map.get("vke").unwrap_or(&0) == 1480 { let mut v = map.entry("b").or_insert(0); *v += 350; }
if *map.get("o").unwrap_or(&0) > 1074 { let mut v = map.entry("o").or_insert(0); *v += 938; }
if *map.get("rz").unwrap_or(&0) == 2053 { let mut v = map.entry("jyi").or_insert(0); *v += -219; }
if *map.get("u").unwrap_or(&0) >= 2162 { let mut v = map.entry("wfu").or_insert(0); *v -= 349; }
if *map.get("o").unwrap_or(&0) > 2025 { let mut v = map.entry("u").or_insert(0); *v -= -97; }
if *map.get("vke").unwrap_or(&0) != 1471 { let mut v = map.entry("pp").or_insert(0); *v += -211; }
if *map.get("b").unwrap_or(&0) < 3699 { let mut v = map.entry("wfu").or_insert(0); *v -= -194; }
if *map.get("sqf").unwrap_or(&0) <= 1980 { let mut v = map.entry("l").or_insert(0); *v -= 96; }
if *map.get("az").unwrap_or(&0) >= 1198 { let mut v = map.entry("vke").or_insert(0); *v -= 179; }
if *map.get("wnh").unwrap_or(&0) != 719 { let mut v = map.entry("vke").or_insert(0); *v -= -317; }
if *map.get("baj").unwrap_or(&0) < -2689 { let mut v = map.entry("tme").or_insert(0); *v += 606; }
if *map.get("fy").unwrap_or(&0) > 1829 { let mut v = map.entry("k").or_insert(0); *v -= 148; }
if *map.get("y").unwrap_or(&0) >= 1041 { let mut v = map.entry("jyi").or_insert(0); *v -= 294; }
if *map.get("xbp").unwrap_or(&0) > -2245 { let mut v = map.entry("wfu").or_insert(0); *v += 963; }
if *map.get("o").unwrap_or(&0) == 2022 { let mut v = map.entry("sb").or_insert(0); *v -= -932; }
if *map.get("c").unwrap_or(&0) <= 316 { let mut v = map.entry("wnh").or_insert(0); *v += -640; }
if *map.get("o").unwrap_or(&0) != 2021 { let mut v = map.entry("rz").or_insert(0); *v += 90; }
if *map.get("rz").unwrap_or(&0) != 2134 { let mut v = map.entry("tme").or_insert(0); *v += 466; }
if *map.get("k").unwrap_or(&0) < -3586 { let mut v = map.entry("l").or_insert(0); *v -= -771; }
if *map.get("e").unwrap_or(&0) <= -551 { let mut v = map.entry("vke").or_insert(0); *v -= 91; }
if *map.get("b").unwrap_or(&0) < 3705 { let mut v = map.entry("fy").or_insert(0); *v -= -312; }
if *map.get("wnh").unwrap_or(&0) >= 71 { let mut v = map.entry("vke").or_insert(0); *v -= -529; }
if *map.get("xml").unwrap_or(&0) < 937 { let mut v = map.entry("b").or_insert(0); *v -= -595; }
if *map.get("b").unwrap_or(&0) != 4293 { let mut v = map.entry("tme").or_insert(0); *v -= 540; }
if *map.get("baj").unwrap_or(&0) <= -2702 { let mut v = map.entry("o").or_insert(0); *v -= 502; }
if *map.get("jyi").unwrap_or(&0) > -1991 { let mut v = map.entry("tme").or_insert(0); *v += -270; }
if *map.get("u").unwrap_or(&0) >= 2157 { let mut v = map.entry("b").or_insert(0); *v -= -298; }
if *map.get("sz").unwrap_or(&0) <= 3813 { let mut v = map.entry("c").or_insert(0); *v -= -599; }
if *map.get("b").unwrap_or(&0) > 4588 { let mut v = map.entry("y").or_insert(0); *v -= -909; }
if *map.get("pp").unwrap_or(&0) != -2201 { let mut v = map.entry("y").or_insert(0); *v += 477; }
if *map.get("u").unwrap_or(&0) < 2163 { let mut v = map.entry("xbp").or_insert(0); *v += 201; }
if *map.get("sb").unwrap_or(&0) >= 636 { let mut v = map.entry("jyi").or_insert(0); *v += 101; }
if *map.get("b").unwrap_or(&0) == 4589 { let mut v = map.entry("l").or_insert(0); *v -= 75; }
if *map.get("e").unwrap_or(&0) <= -558 { let mut v = map.entry("e").or_insert(0); *v += -15; }
if *map.get("sb").unwrap_or(&0) != 638 { let mut v = map.entry("fy").or_insert(0); *v += -471; }
if *map.get("u").unwrap_or(&0) < 2167 { let mut v = map.entry("jyi").or_insert(0); *v += 715; }
if *map.get("az").unwrap_or(&0) == 1203 { let mut v = map.entry("pp").or_insert(0); *v -= 364; }
if *map.get("sqf").unwrap_or(&0) >= 1988 { let mut v = map.entry("az").or_insert(0); *v -= -740; }
if *map.get("wnh").unwrap_or(&0) < 75 { let mut v = map.entry("tme").or_insert(0); *v += 772; }
if *map.get("u").unwrap_or(&0) > 2156 { let mut v = map.entry("k").or_insert(0); *v -= 634; }
if *map.get("u").unwrap_or(&0) <= 2162 { let mut v = map.entry("eia").or_insert(0); *v -= 141; }
if *map.get("l").unwrap_or(&0) < -1184 { let mut v = map.entry("baj").or_insert(0); *v -= 776; }
if *map.get("fy").unwrap_or(&0) <= 1677 { let mut v = map.entry("wnh").or_insert(0); *v -= -920; }
if *map.get("c").unwrap_or(&0) <= 320 { let mut v = map.entry("xbp").or_insert(0); *v -= 169; }
if *map.get("vke").unwrap_or(&0) < 1736 { let mut v = map.entry("sqf").or_insert(0); *v += -193; }
if *map.get("vke").unwrap_or(&0) > 1724 { let mut v = map.entry("fy").or_insert(0); *v -= 96; }
if *map.get("az").unwrap_or(&0) < 1206 { let mut v = map.entry("u").or_insert(0); *v += -282; }
if *map.get("wnh").unwrap_or(&0) != 1000 { let mut v = map.entry("xml").or_insert(0); *v += -395; }
if *map.get("k").unwrap_or(&0) <= -4233 { let mut v = map.entry("az").or_insert(0); *v += -492; }
if *map.get("u").unwrap_or(&0) < 1883 { let mut v = map.entry("sz").or_insert(0); *v += -210; }
if *map.get("eia").unwrap_or(&0) == -2380 { let mut v = map.entry("c").or_insert(0); *v += -584; }
if *map.get("wnh").unwrap_or(&0) >= 994 { let mut v = map.entry("pp").or_insert(0); *v += -772; }
if *map.get("xml").unwrap_or(&0) >= 528 { let mut v = map.entry("ugc").or_insert(0); *v += -946; }
if *map.get("rz").unwrap_or(&0) < 2147 { let mut v = map.entry("l").or_insert(0); *v -= -848; }
if *map.get("sqf").unwrap_or(&0) > 1780 { let mut v = map.entry("o").or_insert(0); *v -= -570; }
if *map.get("e").unwrap_or(&0) < -564 { let mut v = map.entry("ugc").or_insert(0); *v += -849; }
if *map.get("pp").unwrap_or(&0) > -3332 { let mut v = map.entry("sb").or_insert(0); *v -= -327; }
if *map.get("u").unwrap_or(&0) != 1869 { let mut v = map.entry("sqf").or_insert(0); *v -= -937; }
if *map.get("o").unwrap_or(&0) >= 2592 { let mut v = map.entry("xbp").or_insert(0); *v += 765; }
if *map.get("fy").unwrap_or(&0) > 1574 { let mut v = map.entry("ugc").or_insert(0); *v += -2; }
if *map.get("y").unwrap_or(&0) < 2432 { let mut v = map.entry("xml").or_insert(0); *v += -976; }
if *map.get("b").unwrap_or(&0) > 4587 { let mut v = map.entry("o").or_insert(0); *v += 762; }
if *map.get("tme").unwrap_or(&0) == -210 { let mut v = map.entry("xml").or_insert(0); *v += 384; }
if *map.get("wnh").unwrap_or(&0) < 1005 { let mut v = map.entry("u").or_insert(0); *v += -612; }
if *map.get("e").unwrap_or(&0) != -582 { let mut v = map.entry("u").or_insert(0); *v += -229; }
if *map.get("wfu").unwrap_or(&0) <= 1989 { let mut v = map.entry("eia").or_insert(0); *v -= 814; }
if *map.get("sb").unwrap_or(&0) > 964 { let mut v = map.entry("fy").or_insert(0); *v += -41; }
if *map.get("wnh").unwrap_or(&0) != 1004 { let mut v = map.entry("fy").or_insert(0); *v -= -487; }
if *map.get("jyi").unwrap_or(&0) < -1164 { let mut v = map.entry("xml").or_insert(0); *v -= -44; }
if *map.get("sqf").unwrap_or(&0) == 2727 { let mut v = map.entry("k").or_insert(0); *v -= 107; }
if *map.get("rz").unwrap_or(&0) < 2141 { let mut v = map.entry("sz").or_insert(0); *v += -819; }
if *map.get("wnh").unwrap_or(&0) < 1009 { let mut v = map.entry("k").or_insert(0); *v += 862; }
if *map.get("b").unwrap_or(&0) == 4592 { let mut v = map.entry("vke").or_insert(0); *v += -935; }
if *map.get("y").unwrap_or(&0) != 2429 { let mut v = map.entry("k").or_insert(0); *v -= -547; }
if *map.get("l").unwrap_or(&0) >= -331 { let mut v = map.entry("k").or_insert(0); *v -= -804; }
if *map.get("jyi").unwrap_or(&0) >= -1178 { let mut v = map.entry("o").or_insert(0); *v -= -869; }
if *map.get("wfu").unwrap_or(&0) != 1986 { let mut v = map.entry("fy").or_insert(0); *v += -527; }
if *map.get("jyi").unwrap_or(&0) <= -1175 { let mut v = map.entry("vke").or_insert(0); *v += -900; }
if *map.get("pp").unwrap_or(&0) < -3322 { let mut v = map.entry("ugc").or_insert(0); *v += 878; }
if *map.get("eia").unwrap_or(&0) > -3192 { let mut v = map.entry("sz").or_insert(0); *v += 96; }
if *map.get("l").unwrap_or(&0) != -346 { let mut v = map.entry("tme").or_insert(0); *v += -888; }
if *map.get("e").unwrap_or(&0) == -574 { let mut v = map.entry("rz").or_insert(0); *v -= -879; }
if *map.get("wfu").unwrap_or(&0) <= 1983 { let mut v = map.entry("y").or_insert(0); *v += -89; }
if *map.get("xml").unwrap_or(&0) <= -21 { let mut v = map.entry("u").or_insert(0); *v -= 106; }
if *map.get("y").unwrap_or(&0) <= 2423 { let mut v = map.entry("az").or_insert(0); *v -= 724; }
if *map.get("wnh").unwrap_or(&0) == 999 { let mut v = map.entry("sb").or_insert(0); *v += -951; }
if *map.get("xbp").unwrap_or(&0) == -1450 { let mut v = map.entry("wnh").or_insert(0); *v += -583; }
if *map.get("c").unwrap_or(&0) >= 311 { let mut v = map.entry("sz").or_insert(0); *v -= -906; }
if *map.get("b").unwrap_or(&0) <= 4583 { let mut v = map.entry("az").or_insert(0); *v += -192; }
if *map.get("vke").unwrap_or(&0) <= 1728 { let mut v = map.entry("l").or_insert(0); *v -= 307; }
if *map.get("xbp").unwrap_or(&0) >= -1455 { let mut v = map.entry("xbp").or_insert(0); *v -= 553; }
if *map.get("tme").unwrap_or(&0) > -1100 { let mut v = map.entry("u").or_insert(0); *v += 581; }
if *map.get("xml").unwrap_or(&0) >= -22 { let mut v = map.entry("e").or_insert(0); *v += 993; }
if *map.get("y").unwrap_or(&0) != 2422 { let mut v = map.entry("baj").or_insert(0); *v -= 484; }
if *map.get("xbp").unwrap_or(&0) <= -2002 { let mut v = map.entry("u").or_insert(0); *v -= 797; }
if *map.get("sqf").unwrap_or(&0) > 2729 { let mut v = map.entry("xml").or_insert(0); *v -= -448; }
if *map.get("wnh").unwrap_or(&0) <= 413 { let mut v = map.entry("l").or_insert(0); *v -= -97; }
if *map.get("baj").unwrap_or(&0) <= -3959 { let mut v = map.entry("c").or_insert(0); *v -= -211; }
if *map.get("xbp").unwrap_or(&0) > -2008 { let mut v = map.entry("k").or_insert(0); *v -= 925; }
if *map.get("c").unwrap_or(&0) == 316 { let mut v = map.entry("wnh").or_insert(0); *v += 198; }
if *map.get("l").unwrap_or(&0) <= -331 { let mut v = map.entry("l").or_insert(0); *v += 22; }
if *map.get("xbp").unwrap_or(&0) <= -2006 { let mut v = map.entry("jyi").or_insert(0); *v += -293; }
if *map.get("y").unwrap_or(&0) <= 2432 { let mut v = map.entry("e").or_insert(0); *v -= 271; }
if *map.get("pp").unwrap_or(&0) > -3327 { let mut v = map.entry("pp").or_insert(0); *v -= 309; }
if *map.get("jyi").unwrap_or(&0) <= -1181 { let mut v = map.entry("c").or_insert(0); *v -= 645; }
if *map.get("y").unwrap_or(&0) <= 2428 { let mut v = map.entry("l").or_insert(0); *v += 706; }
if *map.get("c").unwrap_or(&0) >= 307 { let mut v = map.entry("xbp").or_insert(0); *v += 477; }
if *map.get("u").unwrap_or(&0) != 811 { let mut v = map.entry("l").or_insert(0); *v += -998; }
if *map.get("az").unwrap_or(&0) != 1193 { let mut v = map.entry("xbp").or_insert(0); *v += 879; }
if *map.get("wfu").unwrap_or(&0) != 1985 { let mut v = map.entry("k").or_insert(0); *v -= 954; }
if *map.get("jyi").unwrap_or(&0) == -1173 { let mut v = map.entry("sb").or_insert(0); *v += -627; }
if *map.get("wnh").unwrap_or(&0) != 614 { let mut v = map.entry("vke").or_insert(0); *v += 766; }
if *map.get("wnh").unwrap_or(&0) != 616 { let mut v = map.entry("pp").or_insert(0); *v += -177; }
if *map.get("wfu").unwrap_or(&0) == 1986 { let mut v = map.entry("y").or_insert(0); *v += -426; }
if *map.get("wfu").unwrap_or(&0) >= 1979 { let mut v = map.entry("wnh").or_insert(0); *v += -932; }
if *map.get("u").unwrap_or(&0) != 821 { let mut v = map.entry("sqf").or_insert(0); *v += 328; }
if *map.get("u").unwrap_or(&0) < 827 { let mut v = map.entry("l").or_insert(0); *v -= -995; }
if *map.get("sb").unwrap_or(&0) < -606 { let mut v = map.entry("xml").or_insert(0); *v += 856; }
if *map.get("b").unwrap_or(&0) >= 4586 { let mut v = map.entry("tme").or_insert(0); *v -= 985; }
if *map.get("wnh").unwrap_or(&0) > -320 { let mut v = map.entry("y").or_insert(0); *v -= 992; }
if *map.get("y").unwrap_or(&0) == 1011 { let mut v = map.entry("baj").or_insert(0); *v -= -833; }
if *map.get("vke").unwrap_or(&0) <= 1735 { let mut v = map.entry("fy").or_insert(0); *v -= -733; }
if *map.get("ugc").unwrap_or(&0) <= -491 { let mut v = map.entry("xml").or_insert(0); *v += 471; }
if *map.get("tme").unwrap_or(&0) < -2082 { let mut v = map.entry("c").or_insert(0); *v -= -970; }
if *map.get("sqf").unwrap_or(&0) != 3051 { let mut v = map.entry("eia").or_insert(0); *v += -404; }
if *map.get("rz").unwrap_or(&0) < 3025 { let mut v = map.entry("sqf").or_insert(0); *v += 646; }
if *map.get("vke").unwrap_or(&0) >= 1729 { let mut v = map.entry("jyi").or_insert(0); *v -= 997; }
if *map.get("pp").unwrap_or(&0) <= -3502 { let mut v = map.entry("c").or_insert(0); *v += 114; }
if *map.get("l").unwrap_or(&0) != -322 { let mut v = map.entry("b").or_insert(0); *v += 385; }
if *map.get("rz").unwrap_or(&0) < 3016 { let mut v = map.entry("ugc").or_insert(0); *v += -76; }
if *map.get("wfu").unwrap_or(&0) == 1986 { let mut v = map.entry("sqf").or_insert(0); *v -= -180; }
if *map.get("jyi").unwrap_or(&0) == -2170 { let mut v = map.entry("jyi").or_insert(0); *v += 876; }
if *map.get("c").unwrap_or(&0) == 1400 { let mut v = map.entry("jyi").or_insert(0); *v += -663; }
if *map.get("sb").unwrap_or(&0) >= -612 { let mut v = map.entry("k").or_insert(0); *v -= -530; }
if *map.get("rz").unwrap_or(&0) < 3032 { let mut v = map.entry("jyi").or_insert(0); *v += 790; }
if *map.get("wnh").unwrap_or(&0) >= -319 { let mut v = map.entry("vke").or_insert(0); *v -= -964; }
if *map.get("ugc").unwrap_or(&0) > -505 { let mut v = map.entry("k").or_insert(0); *v += 165; }
if *map.get("vke").unwrap_or(&0) > 2684 { let mut v = map.entry("xml").or_insert(0); *v -= -928; }
if *map.get("e").unwrap_or(&0) < 155 { let mut v = map.entry("pp").or_insert(0); *v += 739; }
if *map.get("baj").unwrap_or(&0) < -3110 { let mut v = map.entry("sz").or_insert(0); *v += 711; }
if *map.get("y").unwrap_or(&0) < 1020 { let mut v = map.entry("o").or_insert(0); *v += -420; }
if *map.get("jyi").unwrap_or(&0) <= -1162 { let mut v = map.entry("xbp").or_insert(0); *v += 362; }
if *map.get("az").unwrap_or(&0) > 1201 { let mut v = map.entry("wnh").or_insert(0); *v += -228; }
if *map.get("xbp").unwrap_or(&0) < -275 { let mut v = map.entry("jyi").or_insert(0); *v += 931; }
if *map.get("wfu").unwrap_or(&0) > 1983 { let mut v = map.entry("rz").or_insert(0); *v += 650; }
if *map.get("k").unwrap_or(&0) > -4667 { let mut v = map.entry("rz").or_insert(0); *v += 136; }
if *map.get("xml").unwrap_or(&0) != 2236 { let mut v = map.entry("c").or_insert(0); *v -= -923; }
if *map.get("u").unwrap_or(&0) == 819 { let mut v = map.entry("az").or_insert(0); *v -= -127; }
if *map.get("baj").unwrap_or(&0) <= -3115 { let mut v = map.entry("fy").or_insert(0); *v -= 717; }
if *map.get("o").unwrap_or(&0) <= 3807 { let mut v = map.entry("eia").or_insert(0); *v += 14; }
if *map.get("sqf").unwrap_or(&0) >= 3879 { let mut v = map.entry("tme").or_insert(0); *v += 928; }
if *map.get("e").unwrap_or(&0) <= 155 { let mut v = map.entry("vke").or_insert(0); *v += -148; }
if *map.get("az").unwrap_or(&0) <= 1337 { let mut v = map.entry("tme").or_insert(0); *v += 959; }
if *map.get("e").unwrap_or(&0) <= 139 { let mut v = map.entry("c").or_insert(0); *v -= 306; }
if *map.get("b").unwrap_or(&0) == 4974 { let mut v = map.entry("vke").or_insert(0); *v += -622; }
if *map.get("sb").unwrap_or(&0) >= -611 { let mut v = map.entry("c").or_insert(0); *v += -818; }
if *map.get("l").unwrap_or(&0) >= -328 { let mut v = map.entry("az").or_insert(0); *v += -107; }
if *map.get("u").unwrap_or(&0) <= 826 { let mut v = map.entry("l").or_insert(0); *v -= 42; }
if *map.get("ugc").unwrap_or(&0) == -508 { let mut v = map.entry("fy").or_insert(0); *v += -175; }
if *map.get("o").unwrap_or(&0) <= 3806 { let mut v = map.entry("e").or_insert(0); *v += 208; }
if *map.get("c").unwrap_or(&0) != 1515 { let mut v = map.entry("fy").or_insert(0); *v += 239; }
if *map.get("wnh").unwrap_or(&0) != -542 { let mut v = map.entry("sz").or_insert(0); *v -= -678; }
if *map.get("e").unwrap_or(&0) < 348 { let mut v = map.entry("sz").or_insert(0); *v -= 660; }
if *map.get("wfu").unwrap_or(&0) > 1982 { let mut v = map.entry("az").or_insert(0); *v -= 636; }
if *map.get("k").unwrap_or(&0) > -4658 { let mut v = map.entry("tme").or_insert(0); *v += -537; }
if *map.get("eia").unwrap_or(&0) <= -3580 { let mut v = map.entry("sb").or_insert(0); *v -= 977; }
if *map.get("b").unwrap_or(&0) < 4982 { let mut v = map.entry("u").or_insert(0); *v += -171; }
if *map.get("baj").unwrap_or(&0) == -3119 { let mut v = map.entry("wnh").or_insert(0); *v += 141; }
if *map.get("l").unwrap_or(&0) == -362 { let mut v = map.entry("rz").or_insert(0); *v += -648; }
if *map.get("eia").unwrap_or(&0) != -3579 { let mut v = map.entry("eia").or_insert(0); *v -= 910; }
if *map.get("l").unwrap_or(&0) != -355 { let mut v = map.entry("sz").or_insert(0); *v -= -202; }
if *map.get("sz").unwrap_or(&0) <= 6214 { let mut v = map.entry("fy").or_insert(0); *v -= -235; }
if *map.get("eia").unwrap_or(&0) == -4491 { let mut v = map.entry("vke").or_insert(0); *v += 635; }
if *map.get("b").unwrap_or(&0) < 4977 { let mut v = map.entry("eia").or_insert(0); *v += -472; }
if *map.get("tme").unwrap_or(&0) < -729 { let mut v = map.entry("k").or_insert(0); *v -= -936; }
if *map.get("eia").unwrap_or(&0) <= -4958 { let mut v = map.entry("u").or_insert(0); *v -= -793; }
if *map.get("jyi").unwrap_or(&0) == -236 { let mut v = map.entry("jyi").or_insert(0); *v += -273; }
if *map.get("u").unwrap_or(&0) == 1441 { let mut v = map.entry("xml").or_insert(0); *v -= 101; }
if *map.get("sz").unwrap_or(&0) > 6205 { let mut v = map.entry("baj").or_insert(0); *v += 553; }
if *map.get("wfu").unwrap_or(&0) <= 1995 { let mut v = map.entry("c").or_insert(0); *v -= -315; }
if *map.get("l").unwrap_or(&0) < -356 { let mut v = map.entry("e").or_insert(0); *v -= 504; }
if *map.get("eia").unwrap_or(&0) > -4968 { let mut v = map.entry("u").or_insert(0); *v -= -563; }
if *map.get("pp").unwrap_or(&0) != -2768 { let mut v = map.entry("wnh").or_insert(0); *v += -81; }
if *map.get("xml").unwrap_or(&0) == 2140 { let mut v = map.entry("rz").or_insert(0); *v -= -784; }
if *map.get("l").unwrap_or(&0) != -366 { let mut v = map.entry("xbp").or_insert(0); *v -= 113; }
if *map.get("vke").unwrap_or(&0) > 2554 { let mut v = map.entry("b").or_insert(0); *v -= -545; }
if *map.get("e").unwrap_or(&0) <= -151 { let mut v = map.entry("c").or_insert(0); *v -= -978; }
if *map.get("eia").unwrap_or(&0) == -4963 { let mut v = map.entry("baj").or_insert(0); *v -= -782; }
if *map.get("pp").unwrap_or(&0) < -2765 { let mut v = map.entry("wnh").or_insert(0); *v -= 524; }
if *map.get("sb").unwrap_or(&0) >= -1587 { let mut v = map.entry("sz").or_insert(0); *v -= 272; }
if *map.get("jyi").unwrap_or(&0) > -519 { let mut v = map.entry("baj").or_insert(0); *v += -501; }
if *map.get("y").unwrap_or(&0) < 1013 { let mut v = map.entry("xml").or_insert(0); *v -= -246; }
if *map.get("xml").unwrap_or(&0) < 2377 { let mut v = map.entry("az").or_insert(0); *v += -607; }
if *map.get("pp").unwrap_or(&0) >= -2769 { let mut v = map.entry("az").or_insert(0); *v -= -25; }
if *map.get("eia").unwrap_or(&0) < -4962 { let mut v = map.entry("pp").or_insert(0); *v -= -488; }
if *map.get("xml").unwrap_or(&0) > 2382 { let mut v = map.entry("b").or_insert(0); *v += -551; }
if *map.get("az").unwrap_or(&0) == 612 { let mut v = map.entry("sz").or_insert(0); *v += 318; }
if *map.get("pp").unwrap_or(&0) == -2278 { let mut v = map.entry("xml").or_insert(0); *v -= -645; }
if *map.get("e").unwrap_or(&0) < -140 { let mut v = map.entry("u").or_insert(0); *v -= 681; }
if *map.get("sb").unwrap_or(&0) >= -1588 { let mut v = map.entry("b").or_insert(0); *v += -690; }
if *map.get("xml").unwrap_or(&0) < 3034 { let mut v = map.entry("baj").or_insert(0); *v -= 927; }
if *map.get("wnh").unwrap_or(&0) >= -1015 { let mut v = map.entry("e").or_insert(0); *v -= 645; }
if *map.get("xbp").unwrap_or(&0) <= -394 { let mut v = map.entry("sqf").or_insert(0); *v -= 621; }
if *map.get("fy").unwrap_or(&0) <= 2513 { let mut v = map.entry("rz").or_insert(0); *v += 963; }
if *map.get("sz").unwrap_or(&0) == 6252 { let mut v = map.entry("tme").or_insert(0); *v -= -163; }
if *map.get("baj").unwrap_or(&0) > -3220 { let mut v = map.entry("vke").or_insert(0); *v += -132; }
if *map.get("sqf").unwrap_or(&0) <= 3265 { let mut v = map.entry("tme").or_insert(0); *v += -151; }
if *map.get("fy").unwrap_or(&0) >= 2505 { let mut v = map.entry("az").or_insert(0); *v -= 47; }
if *map.get("vke").unwrap_or(&0) > 2421 { let mut v = map.entry("u").or_insert(0); *v += -185; }
if *map.get("sb").unwrap_or(&0) != -1582 { let mut v = map.entry("jyi").or_insert(0); *v += 785; }
if *map.get("e").unwrap_or(&0) > -795 { let mut v = map.entry("k").or_insert(0); *v -= -427; }
if *map.get("xbp").unwrap_or(&0) != -395 { let mut v = map.entry("sz").or_insert(0); *v -= 652; }
if *map.get("eia").unwrap_or(&0) >= -4967 { let mut v = map.entry("eia").or_insert(0); *v += -102; }
if *map.get("wfu").unwrap_or(&0) < 1990 { let mut v = map.entry("b").or_insert(0); *v += -860; }
if *map.get("b").unwrap_or(&0) > 3416 { let mut v = map.entry("rz").or_insert(0); *v -= -501; }
if *map.get("pp").unwrap_or(&0) == -2278 { let mut v = map.entry("y").or_insert(0); *v -= -772; }
if *map.get("y").unwrap_or(&0) >= 1777 { let mut v = map.entry("sz").or_insert(0); *v -= -982; }
if *map.get("fy").unwrap_or(&0) != 2510 { let mut v = map.entry("rz").or_insert(0); *v += 874; }
if *map.get("rz").unwrap_or(&0) < 5410 { let mut v = map.entry("fy").or_insert(0); *v += 965; }
if *map.get("c").unwrap_or(&0) < 1830 { let mut v = map.entry("sb").or_insert(0); *v += 303; }
if *map.get("wnh").unwrap_or(&0) == -1010 { let mut v = map.entry("pp").or_insert(0); *v += 658; }
if *map.get("xml").unwrap_or(&0) > 3029 { let mut v = map.entry("fy").or_insert(0); *v += 206; }
if *map.get("az").unwrap_or(&0) > 558 { let mut v = map.entry("fy").or_insert(0); *v -= 60; }
if *map.get("jyi").unwrap_or(&0) != 276 { let mut v = map.entry("xbp").or_insert(0); *v += -260; }
if *map.get("e").unwrap_or(&0) >= -799 { let mut v = map.entry("xbp").or_insert(0); *v += 398; }
if *map.get("xml").unwrap_or(&0) < 3036 { let mut v = map.entry("sb").or_insert(0); *v -= -532; }
if *map.get("az").unwrap_or(&0) != 565 { let mut v = map.entry("wfu").or_insert(0); *v += -63; }
if *map.get("xbp").unwrap_or(&0) <= 0 { let mut v = map.entry("ugc").or_insert(0); *v += -898; }
if *map.get("e").unwrap_or(&0) < -789 { let mut v = map.entry("rz").or_insert(0); *v -= 875; }
if *map.get("az").unwrap_or(&0) < 558 { let mut v = map.entry("l").or_insert(0); *v += -517; }
if *map.get("u").unwrap_or(&0) == 1138 { let mut v = map.entry("wnh").or_insert(0); *v -= 936; }
if *map.get("pp").unwrap_or(&0) >= -1623 { let mut v = map.entry("k").or_insert(0); *v += 665; }
if *map.get("rz").unwrap_or(&0) == 4533 { let mut v = map.entry("xbp").or_insert(0); *v += 200; }
if *map.get("b").unwrap_or(&0) < 3428 { let mut v = map.entry("k").or_insert(0); *v += 521; }
if *map.get("baj").unwrap_or(&0) >= -3215 { let mut v = map.entry("baj").or_insert(0); *v -= -634; }
if *map.get("rz").unwrap_or(&0) > 4523 { let mut v = map.entry("l").or_insert(0); *v -= 265; }
if *map.get("l").unwrap_or(&0) >= -624 { let mut v = map.entry("sb").or_insert(0); *v -= -725; }
if *map.get("wnh").unwrap_or(&0) < -1944 { let mut v = map.entry("eia").or_insert(0); *v += 959; }
if *map.get("b").unwrap_or(&0) == 3418 { let mut v = map.entry("rz").or_insert(0); *v -= 721; }
if *map.get("sb").unwrap_or(&0) <= -746 { let mut v = map.entry("sqf").or_insert(0); *v += -659; }
if *map.get("sb").unwrap_or(&0) == -752 { let mut v = map.entry("pp").or_insert(0); *v -= -30; }
if *map.get("b").unwrap_or(&0) <= 3424 { let mut v = map.entry("sqf").or_insert(0); *v -= 938; }
if *map.get("k").unwrap_or(&0) < -2108 { let mut v = map.entry("k").or_insert(0); *v += 166; }
if *map.get("o").unwrap_or(&0) >= 3799 { let mut v = map.entry("u").or_insert(0); *v -= 392; }
if *map.get("tme").unwrap_or(&0) == -721 { let mut v = map.entry("l").or_insert(0); *v += -784; }
if *map.get("pp").unwrap_or(&0) >= -1596 { let mut v = map.entry("sb").or_insert(0); *v -= 217; }
if *map.get("b").unwrap_or(&0) == 3418 { let mut v = map.entry("wnh").or_insert(0); *v -= -926; }
if *map.get("rz").unwrap_or(&0) < 3821 { let mut v = map.entry("u").or_insert(0); *v += -7; }
if *map.get("baj").unwrap_or(&0) >= -2582 { let mut v = map.entry("sb").or_insert(0); *v -= -197; }
if *map.get("vke").unwrap_or(&0) > 2419 { let mut v = map.entry("u").or_insert(0); *v += -449; }
if *map.get("c").unwrap_or(&0) <= 1827 { let mut v = map.entry("c").or_insert(0); *v -= 688; }
if *map.get("sz").unwrap_or(&0) < 6578 { let mut v = map.entry("fy").or_insert(0); *v -= 53; }
if *map.get("jyi").unwrap_or(&0) < 284 { let mut v = map.entry("c").or_insert(0); *v -= 687; }
if *map.get("tme").unwrap_or(&0) == -721 { let mut v = map.entry("pp").or_insert(0); *v -= -391; }
if *map.get("ugc").unwrap_or(&0) <= -1392 { let mut v = map.entry("pp").or_insert(0); *v -= 695; }
if *map.get("e").unwrap_or(&0) > -803 { let mut v = map.entry("xbp").or_insert(0); *v -= 132; }
if *map.get("eia").unwrap_or(&0) > -4111 { let mut v = map.entry("e").or_insert(0); *v -= 215; }
if *map.get("eia").unwrap_or(&0) > -4112 { let mut v = map.entry("sb").or_insert(0); *v -= 602; }
if *map.get("baj").unwrap_or(&0) == -2578 { let mut v = map.entry("xbp").or_insert(0); *v += -885; }
if *map.get("sqf").unwrap_or(&0) >= 1655 { let mut v = map.entry("vke").or_insert(0); *v -= -709; }
if *map.get("xbp").unwrap_or(&0) > -819 { let mut v = map.entry("az").or_insert(0); *v -= -378; }
if *map.get("sb").unwrap_or(&0) != -1368 { let mut v = map.entry("vke").or_insert(0); *v -= -263; }
if *map.get("l").unwrap_or(&0) >= -1413 { let mut v = map.entry("baj").or_insert(0); *v -= -783; }
if *map.get("c").unwrap_or(&0) != 442 { let mut v = map.entry("k").or_insert(0); *v += 792; }
if *map.get("sb").unwrap_or(&0) < -1368 { let mut v = map.entry("c").or_insert(0); *v += -31; }
if *map.get("rz").unwrap_or(&0) < 3821 { let mut v = map.entry("sb").or_insert(0); *v -= 904; }
if *map.get("eia").unwrap_or(&0) == -4106 { let mut v = map.entry("fy").or_insert(0); *v += 167; }
if *map.get("e").unwrap_or(&0) > -999 { let mut v = map.entry("xml").or_insert(0); *v += -764; }
if *map.get("baj").unwrap_or(&0) <= -1794 { let mut v = map.entry("wnh").or_insert(0); *v -= -530; }
if *map.get("e").unwrap_or(&0) >= -998 { let mut v = map.entry("jyi").or_insert(0); *v -= -748; }
if *map.get("e").unwrap_or(&0) >= -1014 { let mut v = map.entry("u").or_insert(0); *v += -653; }
if *map.get("l").unwrap_or(&0) <= -1403 { let mut v = map.entry("tme").or_insert(0); *v += -791; }
if *map.get("e").unwrap_or(&0) == -1008 { let mut v = map.entry("fy").or_insert(0); *v -= -800; }
if *map.get("k").unwrap_or(&0) < -1313 { let mut v = map.entry("az").or_insert(0); *v -= 783; }
if *map.get("pp").unwrap_or(&0) >= -1900 { let mut v = map.entry("e").or_insert(0); *v += -553; }
if *map.get("baj").unwrap_or(&0) < -1802 { let mut v = map.entry("wfu").or_insert(0); *v -= -472; }
if *map.get("b").unwrap_or(&0) >= 3427 { let mut v = map.entry("xbp").or_insert(0); *v -= -53; }
if *map.get("xbp").unwrap_or(&0) < -816 { let mut v = map.entry("fy").or_insert(0); *v -= 174; }
if *map.get("vke").unwrap_or(&0) < 3406 { let mut v = map.entry("o").or_insert(0); *v -= 581; }
if *map.get("y").unwrap_or(&0) <= 1785 { let mut v = map.entry("k").or_insert(0); *v += -458; }
if *map.get("az").unwrap_or(&0) == 160 { let mut v = map.entry("az").or_insert(0); *v += 59; }
if *map.get("wfu").unwrap_or(&0) > 1978 { let mut v = map.entry("tme").or_insert(0); *v += 291; }
if *map.get("wfu").unwrap_or(&0) >= 1989 { let mut v = map.entry("pp").or_insert(0); *v -= -933; }
if *map.get("l").unwrap_or(&0) >= -1415 { let mut v = map.entry("jyi").or_insert(0); *v -= -982; }
if *map.get("jyi").unwrap_or(&0) == 1258 { let mut v = map.entry("pp").or_insert(0); *v += 403; }
if *map.get("pp").unwrap_or(&0) >= -1491 { let mut v = map.entry("l").or_insert(0); *v += -149; }
if *map.get("sb").unwrap_or(&0) < -2275 { let mut v = map.entry("fy").or_insert(0); *v -= -663; }
if *map.get("vke").unwrap_or(&0) >= 3401 { let mut v = map.entry("vke").or_insert(0); *v += -866; }
if *map.get("l").unwrap_or(&0) < -1553 { let mut v = map.entry("sqf").or_insert(0); *v -= -397; }
if *map.get("wfu").unwrap_or(&0) > 1981 { let mut v = map.entry("xbp").or_insert(0); *v += 1000; }
if *map.get("wfu").unwrap_or(&0) >= 1979 { let mut v = map.entry("wnh").or_insert(0); *v += -188; }
if *map.get("l").unwrap_or(&0) > -1569 { let mut v = map.entry("l").or_insert(0); *v -= -260; }
if *map.get("xml").unwrap_or(&0) <= 3033 { let mut v = map.entry("baj").or_insert(0); *v += 109; }
if *map.get("rz").unwrap_or(&0) < 3820 { let mut v = map.entry("wfu").or_insert(0); *v -= -98; }
if *map.get("c").unwrap_or(&0) < 417 { let mut v = map.entry("az").or_insert(0); *v += -676; }
if *map.get("wfu").unwrap_or(&0) != 2083 { let mut v = map.entry("e").or_insert(0); *v -= -459; }
if *map.get("sz").unwrap_or(&0) >= 6586 { let mut v = map.entry("sb").or_insert(0); *v += -556; }
if *map.get("pp").unwrap_or(&0) != -1490 { let mut v = map.entry("l").or_insert(0); *v -= -104; }
if *map.get("e").unwrap_or(&0) < -1096 { let mut v = map.entry("jyi").or_insert(0); *v -= 835; }
if *map.get("wfu").unwrap_or(&0) < 2094 { let mut v = map.entry("u").or_insert(0); *v += 63; }
if *map.get("ugc").unwrap_or(&0) > -1405 { let mut v = map.entry("k").or_insert(0); *v -= 531; }
if *map.get("xbp").unwrap_or(&0) < 184 { let mut v = map.entry("wfu").or_insert(0); *v -= 438; }
if *map.get("sz").unwrap_or(&0) < 6589 { let mut v = map.entry("wnh").or_insert(0); *v -= 304; }
if *map.get("ugc").unwrap_or(&0) <= -1391 { let mut v = map.entry("xml").or_insert(0); *v += -278; }
if *map.get("y").unwrap_or(&0) == 1783 { let mut v = map.entry("pp").or_insert(0); *v += -25; }
if *map.get("xml").unwrap_or(&0) == 2753 { let mut v = map.entry("k").or_insert(0); *v -= 179; }
if *map.get("u").unwrap_or(&0) > -303 { let mut v = map.entry("wfu").or_insert(0); *v -= 711; }
if *map.get("wfu").unwrap_or(&0) >= 931 { let mut v = map.entry("eia").or_insert(0); *v -= 575; }
if *map.get("ugc").unwrap_or(&0) <= -1398 { let mut v = map.entry("sb").or_insert(0); *v += -1; }
if *map.get("xml").unwrap_or(&0) >= 2751 { let mut v = map.entry("pp").or_insert(0); *v -= -948; }
if *map.get("pp").unwrap_or(&0) >= -558 { let mut v = map.entry("xbp").or_insert(0); *v -= -441; }
if *map.get("fy").unwrap_or(&0) == 5077 { let mut v = map.entry("baj").or_insert(0); *v += -558; }
if *map.get("sqf").unwrap_or(&0) < 2063 { let mut v = map.entry("c").or_insert(0); *v -= -901; }
if *map.get("jyi").unwrap_or(&0) >= 420 { let mut v = map.entry("xml").or_insert(0); *v -= 572; }
if *map.get("sqf").unwrap_or(&0) >= 2051 { let mut v = map.entry("c").or_insert(0); *v -= -286; }
if *map.get("tme").unwrap_or(&0) >= -1221 { let mut v = map.entry("az").or_insert(0); *v += 1; }
if *map.get("eia").unwrap_or(&0) > -4682 { let mut v = map.entry("c").or_insert(0); *v -= 551; }
if *map.get("xml").unwrap_or(&0) == 2181 { let mut v = map.entry("sz").or_insert(0); *v -= 261; }
if *map.get("l").unwrap_or(&0) >= -1192 { let mut v = map.entry("b").or_insert(0); *v -= 354; }
if *map.get("xbp").unwrap_or(&0) != 188 { let mut v = map.entry("jyi").or_insert(0); *v += 34; }
if *map.get("wfu").unwrap_or(&0) == 935 { let mut v = map.entry("wnh").or_insert(0); *v += -591; }
if *map.get("rz").unwrap_or(&0) > 3807 { let mut v = map.entry("eia").or_insert(0); *v += 639; }
if *map.get("sz").unwrap_or(&0) != 6320 { let mut v = map.entry("sqf").or_insert(0); *v += 211; }
if *map.get("baj").unwrap_or(&0) < -2241 { let mut v = map.entry("fy").or_insert(0); *v += 310; }
if *map.get("az").unwrap_or(&0) < -451 { let mut v = map.entry("fy").or_insert(0); *v += -680; }
if *map.get("pp").unwrap_or(&0) == -576 { let mut v = map.entry("b").or_insert(0); *v += -352; }
if *map.get("sqf").unwrap_or(&0) != 2280 { let mut v = map.entry("k").or_insert(0); *v -= -704; }
if *map.get("c").unwrap_or(&0) == 1050 { let mut v = map.entry("ugc").or_insert(0); *v += -664; }
if *map.get("e").unwrap_or(&0) < -1103 { let mut v = map.entry("eia").or_insert(0); *v += -501; }
if *map.get("b").unwrap_or(&0) >= 3414 { let mut v = map.entry("u").or_insert(0); *v -= 943; }
if *map.get("sb").unwrap_or(&0) >= -2284 { let mut v = map.entry("baj").or_insert(0); *v += -20; }
if *map.get("jyi").unwrap_or(&0) > 461 { let mut v = map.entry("eia").or_insert(0); *v -= 571; }
if *map.get("o").unwrap_or(&0) > 3212 { let mut v = map.entry("u").or_insert(0); *v -= 642; }
if *map.get("rz").unwrap_or(&0) >= 3808 { let mut v = map.entry("b").or_insert(0); *v += -212; }
if *map.get("wfu").unwrap_or(&0) < 926 { let mut v = map.entry("k").or_insert(0); *v -= -305; }
if *map.get("k").unwrap_or(&0) >= -1784 { let mut v = map.entry("eia").or_insert(0); *v -= -47; }
if *map.get("sz").unwrap_or(&0) > 6316 { let mut v = map.entry("u").or_insert(0); *v += -15; }
if *map.get("xml").unwrap_or(&0) <= 2184 { let mut v = map.entry("ugc").or_insert(0); *v += -61; }
if *map.get("fy").unwrap_or(&0) > 4700 { let mut v = map.entry("sz").or_insert(0); *v -= 663; }
if *map.get("k").unwrap_or(&0) == -1780 { let mut v = map.entry("vke").or_insert(0); *v -= -340; }
if *map.get("l").unwrap_or(&0) >= -1188 { let mut v = map.entry("eia").or_insert(0); *v -= 103; }
if *map.get("wfu").unwrap_or(&0) != 928 { let mut v = map.entry("vke").or_insert(0); *v += -941; }
if *map.get("rz").unwrap_or(&0) > 3813 { let mut v = map.entry("baj").or_insert(0); *v += 323; }
if *map.get("wnh").unwrap_or(&0) != -1573 { let mut v = map.entry("fy").or_insert(0); *v -= 41; }
if *map.get("pp").unwrap_or(&0) >= -573 { let mut v = map.entry("jyi").or_insert(0); *v += 20; }
if *map.get("e").unwrap_or(&0) != -1099 { let mut v = map.entry("o").or_insert(0); *v -= -656; }
if *map.get("tme").unwrap_or(&0) >= -1225 { let mut v = map.entry("sb").or_insert(0); *v -= 473; }
if *map.get("vke").unwrap_or(&0) != 2797 { let mut v = map.entry("b").or_insert(0); *v -= 622; }
if *map.get("tme").unwrap_or(&0) < -1221 { let mut v = map.entry("c").or_insert(0); *v += 484; }
if *map.get("y").unwrap_or(&0) > 1780 { let mut v = map.entry("rz").or_insert(0); *v += 363; }
if *map.get("e").unwrap_or(&0) != -1105 { let mut v = map.entry("b").or_insert(0); *v += -74; }
if *map.get("k").unwrap_or(&0) < -1784 { let mut v = map.entry("sz").or_insert(0); *v -= -38; }
if *map.get("xbp").unwrap_or(&0) <= 192 { let mut v = map.entry("b").or_insert(0); *v -= -518; }
if *map.get("sqf").unwrap_or(&0) >= 2265 { let mut v = map.entry("xbp").or_insert(0); *v += -795; }
if *map.get("baj").unwrap_or(&0) >= -2268 { let mut v = map.entry("u").or_insert(0); *v += -484; }
if *map.get("wfu").unwrap_or(&0) == 935 { let mut v = map.entry("fy").or_insert(0); *v -= 302; }
if *map.get("wnh").unwrap_or(&0) == -1566 { let mut v = map.entry("k").or_insert(0); *v -= 643; }
if *map.get("xbp").unwrap_or(&0) < -611 { let mut v = map.entry("wnh").or_insert(0); *v += 16; }
if *map.get("pp").unwrap_or(&0) >= -575 { let mut v = map.entry("eia").or_insert(0); *v -= 289; }
if *map.get("rz").unwrap_or(&0) == 4175 { let mut v = map.entry("b").or_insert(0); *v += 673; }
if *map.get("wfu").unwrap_or(&0) <= 935 { let mut v = map.entry("wnh").or_insert(0); *v += 305; }
if *map.get("wfu").unwrap_or(&0) == 935 { let mut v = map.entry("b").or_insert(0); *v += 18; }
if *map.get("pp").unwrap_or(&0) == -568 { let mut v = map.entry("az").or_insert(0); *v += 810; }
if *map.get("pp").unwrap_or(&0) >= -559 { let mut v = map.entry("sb").or_insert(0); *v -= -609; }
if *map.get("ugc").unwrap_or(&0) >= -2122 { let mut v = map.entry("sz").or_insert(0); *v -= 311; }
if *map.get("wnh").unwrap_or(&0) == -1252 { let mut v = map.entry("wfu").or_insert(0); *v -= -836; }
if *map.get("baj").unwrap_or(&0) <= -2270 { let mut v = map.entry("wfu").or_insert(0); *v -= -78; }
if *map.get("wfu").unwrap_or(&0) < 1779 { let mut v = map.entry("baj").or_insert(0); *v -= -186; }
if *map.get("tme").unwrap_or(&0) > -1220 { let mut v = map.entry("c").or_insert(0); *v -= -129; }
if *map.get("tme").unwrap_or(&0) != -1214 { let mut v = map.entry("fy").or_insert(0); *v -= 662; }
if *map.get("u").unwrap_or(&0) != -2394 { let mut v = map.entry("jyi").or_insert(0); *v += 624; }
if *map.get("pp").unwrap_or(&0) != -573 { let mut v = map.entry("sb").or_insert(0); *v += -906; }
if *map.get("wfu").unwrap_or(&0) >= 1780 { let mut v = map.entry("rz").or_insert(0); *v -= -263; }
if *map.get("xml").unwrap_or(&0) > 2179 { let mut v = map.entry("k").or_insert(0); *v += -364; }
if *map.get("ugc").unwrap_or(&0) < -2117 { let mut v = map.entry("rz").or_insert(0); *v -= 214; }
if *map.get("xbp").unwrap_or(&0) < -606 { let mut v = map.entry("o").or_insert(0); *v -= -539; }
if *map.get("l").unwrap_or(&0) <= -1188 { let mut v = map.entry("wnh").or_insert(0); *v += -708; }
if *map.get("y").unwrap_or(&0) != 1785 { let mut v = map.entry("sqf").or_insert(0); *v -= -901; }
if *map.get("c").unwrap_or(&0) != 1048 { let mut v = map.entry("ugc").or_insert(0); *v -= 0; }
if *map.get("b").unwrap_or(&0) < 4338 { let mut v = map.entry("wnh").or_insert(0); *v -= 712; }
if *map.get("baj").unwrap_or(&0) < -2086 { let mut v = map.entry("wnh").or_insert(0); *v -= -554; }
if *map.get("baj").unwrap_or(&0) == -2078 { let mut v = map.entry("sb").or_insert(0); *v -= 777; }
if *map.get("c").unwrap_or(&0) > 1046 { let mut v = map.entry("l").or_insert(0); *v -= 713; }
if *map.get("eia").unwrap_or(&0) == -4284 { let mut v = map.entry("o").or_insert(0); *v += 44; }
if *map.get("o").unwrap_or(&0) != 4456 { let mut v = map.entry("rz").or_insert(0); *v += 77; }
if *map.get("az").unwrap_or(&0) > 346 { let mut v = map.entry("xml").or_insert(0); *v += 862; }
if *map.get("k").unwrap_or(&0) > -2151 { let mut v = map.entry("wfu").or_insert(0); *v -= 242; }
if *map.get("k").unwrap_or(&0) >= -2152 { let mut v = map.entry("b").or_insert(0); *v -= 998; }
if *map.get("o").unwrap_or(&0) != 4460 { let mut v = map.entry("sz").or_insert(0); *v -= 202; }
if *map.get("wfu").unwrap_or(&0) < 1537 { let mut v = map.entry("tme").or_insert(0); *v += 941; }
if *map.get("c").unwrap_or(&0) == 1050 { let mut v = map.entry("pp").or_insert(0); *v += -536; }
if *map.get("y").unwrap_or(&0) != 1781 { let mut v = map.entry("wfu").or_insert(0); *v += 557; }
if *map.get("y").unwrap_or(&0) != 1783 { let mut v = map.entry("e").or_insert(0); *v += -982; }
if *map.get("y").unwrap_or(&0) != 1790 { let mut v = map.entry("u").or_insert(0); *v -= -49; }
if *map.get("jyi").unwrap_or(&0) <= 1102 { let mut v = map.entry("az").or_insert(0); *v += 602; }
if *map.get("c").unwrap_or(&0) != 1040 { let mut v = map.entry("e").or_insert(0); *v += -457; }
if *map.get("tme").unwrap_or(&0) < -279 { let mut v = map.entry("wnh").or_insert(0); *v += 914; }
if *map.get("c").unwrap_or(&0) == 1050 { let mut v = map.entry("tme").or_insert(0); *v += -262; }
if *map.get("c").unwrap_or(&0) == 1050 { let mut v = map.entry("c").or_insert(0); *v += -611; }
if *map.get("az").unwrap_or(&0) >= 953 { let mut v = map.entry("xml").or_insert(0); *v += 921; }
if *map.get("k").unwrap_or(&0) > -2148 { let mut v = map.entry("tme").or_insert(0); *v += -910; }
if *map.get("o").unwrap_or(&0) >= 4452 { let mut v = map.entry("xml").or_insert(0); *v += 994; }
if *map.get("xbp").unwrap_or(&0) == -612 { let mut v = map.entry("c").or_insert(0); *v += 433; }
if *map.get("jyi").unwrap_or(&0) == 1101 { let mut v = map.entry("wfu").or_insert(0); *v -= 591; }
if *map.get("wnh").unwrap_or(&0) < -1045 { let mut v = map.entry("jyi").or_insert(0); *v -= -916; }
if *map.get("jyi").unwrap_or(&0) == 2007 { let mut v = map.entry("eia").or_insert(0); *v -= -514; }
if *map.get("o").unwrap_or(&0) <= 4463 { let mut v = map.entry("tme").or_insert(0); *v -= -305; }
if *map.get("baj").unwrap_or(&0) <= -2076 { let mut v = map.entry("c").or_insert(0); *v -= -404; }
if *map.get("wfu").unwrap_or(&0) > 1501 { let mut v = map.entry("rz").or_insert(0); *v -= -942; }
if *map.get("k").unwrap_or(&0) == -2144 { let mut v = map.entry("xbp").or_insert(0); *v += 286; }
if *map.get("fy").unwrap_or(&0) >= 3743 { let mut v = map.entry("xbp").or_insert(0); *v += -119; }
if *map.get("baj").unwrap_or(&0) != -2074 { let mut v = map.entry("ugc").or_insert(0); *v += 171; }
if *map.get("xbp").unwrap_or(&0) < -443 { let mut v = map.entry("l").or_insert(0); *v -= -784; }
if *map.get("sqf").unwrap_or(&0) < 3173 { let mut v = map.entry("ugc").or_insert(0); *v -= 146; }
if *map.get("c").unwrap_or(&0) > 1272 { let mut v = map.entry("c").or_insert(0); *v -= 397; }
if *map.get("fy").unwrap_or(&0) != 3743 { let mut v = map.entry("k").or_insert(0); *v -= 468; }
if *map.get("sz").unwrap_or(&0) == 5145 { let mut v = map.entry("wnh").or_insert(0); *v += -174; }
if *map.get("eia").unwrap_or(&0) == -4284 { let mut v = map.entry("u").or_insert(0); *v -= -225; }
if *map.get("fy").unwrap_or(&0) == 3743 { let mut v = map.entry("sqf").or_insert(0); *v += 687; }
if *map.get("jyi").unwrap_or(&0) == 2008 { let mut v = map.entry("e").or_insert(0); *v += 705; }
if *map.get("c").unwrap_or(&0) <= 887 { let mut v = map.entry("wfu").or_insert(0); *v += -904; }
if *map.get("wfu").unwrap_or(&0) <= 597 { let mut v = map.entry("jyi").or_insert(0); *v -= -593; }
if *map.get("e").unwrap_or(&0) < -1554 { let mut v = map.entry("tme").or_insert(0); *v += 807; }
if *map.get("az").unwrap_or(&0) > 946 { let mut v = map.entry("fy").or_insert(0); *v += -497; }
if *map.get("sz").unwrap_or(&0) == 5146 { let mut v = map.entry("rz").or_insert(0); *v += -921; }
if *map.get("wfu").unwrap_or(&0) >= 591 { let mut v = map.entry("az").or_insert(0); *v -= -401; }
if *map.get("k").unwrap_or(&0) > -2149 { let mut v = map.entry("sz").or_insert(0); *v -= 728; }
if *map.get("vke").unwrap_or(&0) <= 2787 { let mut v = map.entry("c").or_insert(0); *v -= 884; }
if *map.get("vke").unwrap_or(&0) <= 2804 { let mut v = map.entry("l").or_insert(0); *v -= 764; }
if *map.get("b").unwrap_or(&0) < 3346 { let mut v = map.entry("xml").or_insert(0); *v -= 226; }
if *map.get("c").unwrap_or(&0) < 879 { let mut v = map.entry("sqf").or_insert(0); *v -= -84; }
if *map.get("e").unwrap_or(&0) <= -1556 { let mut v = map.entry("eia").or_insert(0); *v += 634; }
if *map.get("az").unwrap_or(&0) >= 1357 { let mut v = map.entry("o").or_insert(0); *v += -473; }
if *map.get("o").unwrap_or(&0) == 3988 { let mut v = map.entry("sb").or_insert(0); *v += 917; }
if *map.get("tme").unwrap_or(&0) >= -334 { let mut v = map.entry("ugc").or_insert(0); *v += 411; }
if *map.get("az").unwrap_or(&0) != 1353 { let mut v = map.entry("jyi").or_insert(0); *v += 214; }
if *map.get("c").unwrap_or(&0) <= 879 { let mut v = map.entry("xbp").or_insert(0); *v += -296; }
if *map.get("sb").unwrap_or(&0) < -3525 { let mut v = map.entry("k").or_insert(0); *v += -416; }
if *map.get("tme").unwrap_or(&0) != -350 { let mut v = map.entry("eia").or_insert(0); *v += -847; }
if *map.get("k").unwrap_or(&0) <= -2139 { let mut v = map.entry("sb").or_insert(0); *v -= 525; }
if *map.get("sz").unwrap_or(&0) > 4415 { let mut v = map.entry("sqf").or_insert(0); *v += -749; }
if *map.get("xbp").unwrap_or(&0) != -749 { let mut v = map.entry("c").or_insert(0); *v += -382; }
if *map.get("wfu").unwrap_or(&0) < 594 { let mut v = map.entry("l").or_insert(0); *v -= -705; }
if *map.get("xbp").unwrap_or(&0) >= -739 { let mut v = map.entry("sz").or_insert(0); *v -= 38; }
if *map.get("xbp").unwrap_or(&0) != -733 { let mut v = map.entry("sqf").or_insert(0); *v -= 431; }
if *map.get("xbp").unwrap_or(&0) >= -748 { let mut v = map.entry("b").or_insert(0); *v += 766; }
if *map.get("tme").unwrap_or(&0) != -341 { let mut v = map.entry("wfu").or_insert(0); *v += -263; }
if *map.get("c").unwrap_or(&0) != 494 { let mut v = map.entry("wnh").or_insert(0); *v += 435; }
if *map.get("vke").unwrap_or(&0) != 2807 { let mut v = map.entry("sqf").or_insert(0); *v -= -207; }
if *map.get("sz").unwrap_or(&0) < 4419 { let mut v = map.entry("sb").or_insert(0); *v += -192; }
if *map.get("wfu").unwrap_or(&0) > 319 { let mut v = map.entry("sb").or_insert(0); *v += 985; }
if *map.get("ugc").unwrap_or(&0) != -2097 { let mut v = map.entry("wfu").or_insert(0); *v += 478; }
if *map.get("rz").unwrap_or(&0) < 4042 { let mut v = map.entry("eia").or_insert(0); *v += -44; }
if *map.get("jyi").unwrap_or(&0) >= 2818 { let mut v = map.entry("u").or_insert(0); *v += 457; }
if *map.get("sb").unwrap_or(&0) == -3249 { let mut v = map.entry("sb").or_insert(0); *v += 929; }
if *map.get("vke").unwrap_or(&0) >= 2793 { let mut v = map.entry("vke").or_insert(0); *v -= -199; }
if *map.get("u").unwrap_or(&0) < -1656 { let mut v = map.entry("sqf").or_insert(0); *v -= -144; }
if *map.get("ugc").unwrap_or(&0) == -2097 { let mut v = map.entry("sqf").or_insert(0); *v -= -917; }
if *map.get("b").unwrap_or(&0) == 4109 { let mut v = map.entry("rz").or_insert(0); *v -= 958; }
if *map.get("vke").unwrap_or(&0) <= 2996 { let mut v = map.entry("k").or_insert(0); *v += -532; }
if *map.get("sqf").unwrap_or(&0) <= 3804 { let mut v = map.entry("y").or_insert(0); *v -= -150; }
if *map.get("u").unwrap_or(&0) == -1651 { let mut v = map.entry("jyi").or_insert(0); *v -= -149; }
if *map.get("wfu").unwrap_or(&0) < 337 { let mut v = map.entry("jyi").or_insert(0); *v -= 939; }
if *map.get("wnh").unwrap_or(&0) <= -782 { let mut v = map.entry("xml").or_insert(0); *v += 266; }
if *map.get("tme").unwrap_or(&0) == -338 { let mut v = map.entry("pp").or_insert(0); *v += 130; }
if *map.get("xml").unwrap_or(&0) > 4994 { let mut v = map.entry("u").or_insert(0); *v += 665; }
if *map.get("tme").unwrap_or(&0) >= -341 { let mut v = map.entry("o").or_insert(0); *v += -510; }
if *map.get("sz").unwrap_or(&0) != 4421 { let mut v = map.entry("k").or_insert(0); *v -= -273; }
if *map.get("wnh").unwrap_or(&0) < -778 { let mut v = map.entry("vke").or_insert(0); *v += 392; }
if *map.get("wfu").unwrap_or(&0) <= 334 { let mut v = map.entry("pp").or_insert(0); *v -= -464; }
if *map.get("xbp").unwrap_or(&0) != -741 { let mut v = map.entry("xml").or_insert(0); *v -= 746; }
if *map.get("eia").unwrap_or(&0) != -4541 { let mut v = map.entry("xml").or_insert(0); *v -= 215; }
if *map.get("sz").unwrap_or(&0) > 4420 { let mut v = map.entry("b").or_insert(0); *v += 26; }
if *map.get("l").unwrap_or(&0) != -1183 { let mut v = map.entry("wnh").or_insert(0); *v += -601; }
if *map.get("xbp").unwrap_or(&0) < -744 { let mut v = map.entry("u").or_insert(0); *v -= -660; }
if *map.get("xml").unwrap_or(&0) < 5004 { let mut v = map.entry("o").or_insert(0); *v -= -362; }
if *map.get("y").unwrap_or(&0) > 1924 { let mut v = map.entry("k").or_insert(0); *v -= 689; }
if *map.get("sb").unwrap_or(&0) <= -2315 { let mut v = map.entry("ugc").or_insert(0); *v -= -245; }
if *map.get("o").unwrap_or(&0) >= 3835 { let mut v = map.entry("rz").or_insert(0); *v += 746; }
if *map.get("baj").unwrap_or(&0) == -2078 { let mut v = map.entry("sqf").or_insert(0); *v += -65; }
if *map.get("az").unwrap_or(&0) > 1365 { let mut v = map.entry("xml").or_insert(0); *v -= -571; }
if *map.get("wnh").unwrap_or(&0) < -1379 { let mut v = map.entry("xml").or_insert(0); *v += -309; }
if *map.get("y").unwrap_or(&0) == 1933 { let mut v = map.entry("wnh").or_insert(0); *v -= -554; }
if *map.get("xbp").unwrap_or(&0) == -741 { let mut v = map.entry("vke").or_insert(0); *v += 542; }
if *map.get("o").unwrap_or(&0) == 3840 { let mut v = map.entry("e").or_insert(0); *v += -386; }
if *map.get("c").unwrap_or(&0) > 495 { let mut v = map.entry("b").or_insert(0); *v += -605; }
if *map.get("sz").unwrap_or(&0) <= 4426 { let mut v = map.entry("az").or_insert(0); *v += -784; }
if *map.get("sz").unwrap_or(&0) < 4418 { let mut v = map.entry("pp").or_insert(0); *v += 308; }
if *map.get("eia").unwrap_or(&0) < -4549 { let mut v = map.entry("c").or_insert(0); *v -= -79; }
if *map.get("b").unwrap_or(&0) >= 3497 { let mut v = map.entry("sb").or_insert(0); *v += 224; }
if *map.get("az").unwrap_or(&0) <= 578 { let mut v = map.entry("rz").or_insert(0); *v -= 681; }
if *map.get("c").unwrap_or(&0) <= 500 { let mut v = map.entry("ugc").or_insert(0); *v += 210; }
if *map.get("o").unwrap_or(&0) < 3834 { let mut v = map.entry("baj").or_insert(0); *v += -271; }
if *map.get("sz").unwrap_or(&0) < 4422 { let mut v = map.entry("l").or_insert(0); *v += 476; }
if *map.get("tme").unwrap_or(&0) >= -345 { let mut v = map.entry("o").or_insert(0); *v -= -432; }
if *map.get("u").unwrap_or(&0) < -982 { let mut v = map.entry("baj").or_insert(0); *v += -713; }
if *map.get("baj").unwrap_or(&0) == -2791 { let mut v = map.entry("u").or_insert(0); *v += -192; }
if *map.get("wnh").unwrap_or(&0) <= -833 { let mut v = map.entry("baj").or_insert(0); *v -= 411; }
if *map.get("y").unwrap_or(&0) == 1933 { let mut v = map.entry("pp").or_insert(0); *v -= 728; }
if *map.get("sb").unwrap_or(&0) != -2096 { let mut v = map.entry("ugc").or_insert(0); *v += -200; }
if *map.get("fy").unwrap_or(&0) == 3252 { let mut v = map.entry("l").or_insert(0); *v -= 787; }
if *map.get("rz").unwrap_or(&0) >= 3136 { let mut v = map.entry("pp").or_insert(0); *v -= -924; }
if *map.get("o").unwrap_or(&0) <= 4280 { let mut v = map.entry("o").or_insert(0); *v += 792; }
if *map.get("u").unwrap_or(&0) < -1171 { let mut v = map.entry("b").or_insert(0); *v -= -300; }
if *map.get("az").unwrap_or(&0) >= 580 { let mut v = map.entry("sqf").or_insert(0); *v -= -328; }
if *map.get("baj").unwrap_or(&0) >= -2799 { let mut v = map.entry("vke").or_insert(0); *v -= 887; }
if *map.get("vke").unwrap_or(&0) == 3050 { let mut v = map.entry("u").or_insert(0); *v += -252; }
if *map.get("eia").unwrap_or(&0) <= -4541 { let mut v = map.entry("o").or_insert(0); *v -= 640; }
if *map.get("wnh").unwrap_or(&0) >= -836 { let mut v = map.entry("sb").or_insert(0); *v += -919; }
if *map.get("wnh").unwrap_or(&0) <= -841 { let mut v = map.entry("l").or_insert(0); *v -= 463; }
if *map.get("b").unwrap_or(&0) <= 3797 { let mut v = map.entry("rz").or_insert(0); *v -= -942; }
if *map.get("fy").unwrap_or(&0) <= 3253 { let mut v = map.entry("az").or_insert(0); *v -= -170; }
if *map.get("eia").unwrap_or(&0) > -4545 { let mut v = map.entry("e").or_insert(0); *v += 718; }
if *map.get("ugc").unwrap_or(&0) <= -1650 { let mut v = map.entry("az").or_insert(0); *v -= 103; }
if *map.get("jyi").unwrap_or(&0) > 1879 { let mut v = map.entry("sqf").or_insert(0); *v += 709; }
if *map.get("c").unwrap_or(&0) == 502 { let mut v = map.entry("pp").or_insert(0); *v += 566; }
if *map.get("sz").unwrap_or(&0) <= 4417 { let mut v = map.entry("e").or_insert(0); *v += -611; }
if *map.get("wfu").unwrap_or(&0) != 328 { let mut v = map.entry("baj").or_insert(0); *v += -998; }
if *map.get("sqf").unwrap_or(&0) < 4450 { let mut v = map.entry("o").or_insert(0); *v -= 891; }
if *map.get("pp").unwrap_or(&0) <= -143 { let mut v = map.entry("sz").or_insert(0); *v -= -86; }
if *map.get("sz").unwrap_or(&0) > 4411 { let mut v = map.entry("xbp").or_insert(0); *v -= 199; }
if *map.get("c").unwrap_or(&0) != 487 { let mut v = map.entry("rz").or_insert(0); *v += -158; }
if *map.get("wfu").unwrap_or(&0) > 324 { let mut v = map.entry("rz").or_insert(0); *v += -710; }
if *map.get("fy").unwrap_or(&0) >= 3241 { let mut v = map.entry("ugc").or_insert(0); *v -= -635; }
if *map.get("az").unwrap_or(&0) <= 738 { let mut v = map.entry("k").or_insert(0); *v += -221; }
if *map.get("e").unwrap_or(&0) > -1839 { let mut v = map.entry("sqf").or_insert(0); *v += -74; }
if *map.get("az").unwrap_or(&0) >= 743 { let mut v = map.entry("az").or_insert(0); *v -= -317; }
if *map.get("tme").unwrap_or(&0) <= -339 { let mut v = map.entry("eia").or_insert(0); *v -= 596; }
if *map.get("wnh").unwrap_or(&0) == -832 { let mut v = map.entry("vke").or_insert(0); *v -= 708; }
if *map.get("sz").unwrap_or(&0) == 4417 { let mut v = map.entry("u").or_insert(0); *v -= 414; }
if *map.get("e").unwrap_or(&0) < -1841 { let mut v = map.entry("y").or_insert(0); *v += 388; }
if *map.get("y").unwrap_or(&0) == 1941 { let mut v = map.entry("xml").or_insert(0); *v += -783; }
if *map.get("c").unwrap_or(&0) < 498 { let mut v = map.entry("o").or_insert(0); *v -= 695; }
if *map.get("baj").unwrap_or(&0) != -2787 { let mut v = map.entry("ugc").or_insert(0); *v -= -944; }
if *map.get("baj").unwrap_or(&0) <= -2787 { let mut v = map.entry("b").or_insert(0); *v += -964; }
if *map.get("sqf").unwrap_or(&0) == 4373 { let mut v = map.entry("vke").or_insert(0); *v -= -208; }
if *map.get("rz").unwrap_or(&0) >= 2274 { let mut v = map.entry("vke").or_insert(0); *v += -206; }
if *map.get("tme").unwrap_or(&0) < -333 { let mut v = map.entry("ugc").or_insert(0); *v += 726; }
if *map.get("ugc").unwrap_or(&0) < 667 { let mut v = map.entry("eia").or_insert(0); *v += 986; }
if *map.get("vke").unwrap_or(&0) < 2343 { let mut v = map.entry("baj").or_insert(0); *v -= -139; }
if *map.get("eia").unwrap_or(&0) != -4156 { let mut v = map.entry("o").or_insert(0); *v -= -19; }
if *map.get("sz").unwrap_or(&0) > 4419 { let mut v = map.entry("wnh").or_insert(0); *v += -396; }
if *map.get("rz").unwrap_or(&0) >= 2277 { let mut v = map.entry("ugc").or_insert(0); *v += -74; }
if *map.get("wnh").unwrap_or(&0) < -828 { let mut v = map.entry("pp").or_insert(0); *v += 239; }
if *map.get("u").unwrap_or(&0) == -1594 { let mut v = map.entry("sz").or_insert(0); *v += -741; }
if *map.get("k").unwrap_or(&0) < -3089 { let mut v = map.entry("c").or_insert(0); *v += 340; }
if *map.get("sqf").unwrap_or(&0) >= 4371 { let mut v = map.entry("xml").or_insert(0); *v -= 156; }
if *map.get("b").unwrap_or(&0) != 2841 { let mut v = map.entry("sqf").or_insert(0); *v -= 433; }
if *map.get("tme").unwrap_or(&0) < -334 { let mut v = map.entry("vke").or_insert(0); *v -= 231; }
if *map.get("eia").unwrap_or(&0) > -4150 { let mut v = map.entry("u").or_insert(0); *v += 393; }
if *map.get("u").unwrap_or(&0) >= -1599 { let mut v = map.entry("xbp").or_insert(0); *v -= -482; }
if *map.get("u").unwrap_or(&0) > -1601 { let mut v = map.entry("fy").or_insert(0); *v += 40; }
if *map.get("sz").unwrap_or(&0) <= 3684 { let mut v = map.entry("baj").or_insert(0); *v -= 29; }
if *map.get("xml").unwrap_or(&0) != 4531 { let mut v = map.entry("sz").or_insert(0); *v -= 874; }
if *map.get("pp").unwrap_or(&0) <= 103 { let mut v = map.entry("ugc").or_insert(0); *v += -50; }
if *map.get("xbp").unwrap_or(&0) == -458 { let mut v = map.entry("sb").or_insert(0); *v -= 96; }
if *map.get("jyi").unwrap_or(&0) != 1894 { let mut v = map.entry("e").or_insert(0); *v += 266; }
if *map.get("y").unwrap_or(&0) == 1933 { let mut v = map.entry("sz").or_insert(0); *v += 336; }
if *map.get("wfu").unwrap_or(&0) > 321 { let mut v = map.entry("eia").or_insert(0); *v -= -592; }
if *map.get("o").unwrap_or(&0) > 2863 { let mut v = map.entry("rz").or_insert(0); *v -= -580; }
if *map.get("l").unwrap_or(&0) != -701 { let mut v = map.entry("xml").or_insert(0); *v -= -468; }
if *map.get("sqf").unwrap_or(&0) == 3940 { let mut v = map.entry("sqf").or_insert(0); *v += -672; }
if *map.get("jyi").unwrap_or(&0) < 1891 { let mut v = map.entry("vke").or_insert(0); *v -= -600; }
if *map.get("baj").unwrap_or(&0) < -2677 { let mut v = map.entry("e").or_insert(0); *v -= -31; }
if *map.get("rz").unwrap_or(&0) != 2275 { let mut v = map.entry("rz").or_insert(0); *v -= -409; }
if *map.get("ugc").unwrap_or(&0) > 536 { let mut v = map.entry("jyi").or_insert(0); *v += 839; }
if *map.get("c").unwrap_or(&0) > 830 { let mut v = map.entry("wfu").or_insert(0); *v += -886; }
if *map.get("l").unwrap_or(&0) == -708 { let mut v = map.entry("vke").or_insert(0); *v += 500; }
if *map.get("tme").unwrap_or(&0) >= -344 { let mut v = map.entry("sz").or_insert(0); *v += 490; }
if *map.get("rz").unwrap_or(&0) != 2684 { let mut v = map.entry("rz").or_insert(0); *v += -478; }
if *map.get("o").unwrap_or(&0) != 2853 { let mut v = map.entry("sqf").or_insert(0); *v += -367; }
if *map.get("u").unwrap_or(&0) <= -1585 { let mut v = map.entry("baj").or_insert(0); *v += -461; }
if *map.get("c").unwrap_or(&0) <= 827 { let mut v = map.entry("fy").or_insert(0); *v -= -642; }
if *map.get("b").unwrap_or(&0) > 2836 { let mut v = map.entry("ugc").or_insert(0); *v += -371; }
if *map.get("jyi").unwrap_or(&0) <= 2727 { let mut v = map.entry("l").or_insert(0); *v += -983; }
if *map.get("wfu").unwrap_or(&0) <= -565 { let mut v = map.entry("b").or_insert(0); *v -= 599; }
if *map.get("baj").unwrap_or(&0) <= -3149 { let mut v = map.entry("rz").or_insert(0); *v += -852; }
if *map.get("c").unwrap_or(&0) != 827 { let mut v = map.entry("sz").or_insert(0); *v -= -453; }
if *map.get("jyi").unwrap_or(&0) < 2725 { let mut v = map.entry("vke").or_insert(0); *v += 631; }
if *map.get("xml").unwrap_or(&0) >= 4996 { let mut v = map.entry("b").or_insert(0); *v += 145; }
if *map.get("ugc").unwrap_or(&0) == 168 { let mut v = map.entry("sqf").or_insert(0); *v += -921; }
if *map.get("xml").unwrap_or(&0) < 5002 { let mut v = map.entry("c").or_insert(0); *v += 933; }
if *map.get("y").unwrap_or(&0) <= 1934 { let mut v = map.entry("l").or_insert(0); *v -= 994; }
if *map.get("wnh").unwrap_or(&0) <= -828 { let mut v = map.entry("eia").or_insert(0); *v -= 59; }
if *map.get("ugc").unwrap_or(&0) >= 166 { let mut v = map.entry("wfu").or_insert(0); *v -= 600; }
if *map.get("az").unwrap_or(&0) > 1050 { let mut v = map.entry("b").or_insert(0); *v -= -316; }
if *map.get("y").unwrap_or(&0) < 1940 { let mut v = map.entry("sz").or_insert(0); *v -= 832; }
if *map.get("fy").unwrap_or(&0) >= 3280 { let mut v = map.entry("fy").or_insert(0); *v -= -517; }
if *map.get("jyi").unwrap_or(&0) <= 2727 { let mut v = map.entry("c").or_insert(0); *v += -801; }
if *map.get("xml").unwrap_or(&0) < 5007 { let mut v = map.entry("xbp").or_insert(0); *v -= 381; }
if *map.get("baj").unwrap_or(&0) >= -3142 { let mut v = map.entry("rz").or_insert(0); *v -= 115; }
if *map.get("tme").unwrap_or(&0) > -332 { let mut v = map.entry("az").or_insert(0); *v += -553; }
if *map.get("rz").unwrap_or(&0) <= 2093 { let mut v = map.entry("wfu").or_insert(0); *v += 837; }
if *map.get("tme").unwrap_or(&0) <= -334 { let mut v = map.entry("ugc").or_insert(0); *v += -490; }
if *map.get("xbp").unwrap_or(&0) >= -843 { let mut v = map.entry("fy").or_insert(0); *v += 645; }
if *map.get("tme").unwrap_or(&0) >= -341 { let mut v = map.entry("tme").or_insert(0); *v += -756; }
if *map.get("e").unwrap_or(&0) != -1543 { let mut v = map.entry("rz").or_insert(0); *v += -987; }
if *map.get("jyi").unwrap_or(&0) > 2715 { let mut v = map.entry("xml").or_insert(0); *v += -423; }
if *map.get("c").unwrap_or(&0) <= 975 { let mut v = map.entry("rz").or_insert(0); *v += 985; }
if *map.get("o").unwrap_or(&0) > 2847 { let mut v = map.entry("ugc").or_insert(0); *v += -698; }
if *map.get("l").unwrap_or(&0) <= -2684 { let mut v = map.entry("rz").or_insert(0); *v -= 498; }
if *map.get("xbp").unwrap_or(&0) != -845 { let mut v = map.entry("baj").or_insert(0); *v -= -826; }
if *map.get("o").unwrap_or(&0) >= 2849 { let mut v = map.entry("k").or_insert(0); *v += 829; }
if *map.get("az").unwrap_or(&0) == 1060 { let mut v = map.entry("xbp").or_insert(0); *v += 632; }
if *map.get("baj").unwrap_or(&0) >= -2321 { let mut v = map.entry("ugc").or_insert(0); *v += 778; }
if *map.get("sz").unwrap_or(&0) == 3249 { let mut v = map.entry("y").or_insert(0); *v += -806; }
if *map.get("y").unwrap_or(&0) != 1120 { let mut v = map.entry("baj").or_insert(0); *v -= -91; }
if *map.get("fy").unwrap_or(&0) == 4448 { let mut v = map.entry("xml").or_insert(0); *v -= 932; }
if *map.get("xbp").unwrap_or(&0) != -207 { let mut v = map.entry("fy").or_insert(0); *v += -682; }
if *map.get("u").unwrap_or(&0) > -1602 { let mut v = map.entry("eia").or_insert(0); *v += -640; }
if *map.get("baj").unwrap_or(&0) == -2225 { let mut v = map.entry("l").or_insert(0); *v += -736; }
if *map.get("l").unwrap_or(&0) >= -3429 { let mut v = map.entry("xbp").or_insert(0); *v += 244; }
if *map.get("sqf").unwrap_or(&0) < 1974 { let mut v = map.entry("pp").or_insert(0); *v += 26; }
if *map.get("e").unwrap_or(&0) != -1541 { let mut v = map.entry("wfu").or_insert(0); *v += -465; }
if *map.get("l").unwrap_or(&0) != -3426 { let mut v = map.entry("e").or_insert(0); *v -= -224; }
if *map.get("sb").unwrap_or(&0) > -3117 { let mut v = map.entry("wfu").or_insert(0); *v -= 424; }
if *map.get("u").unwrap_or(&0) > -1597 { let mut v = map.entry("wfu").or_insert(0); *v += 699; }
if *map.get("b").unwrap_or(&0) > 3298 { let mut v = map.entry("ugc").or_insert(0); *v -= -222; }
if *map.get("c").unwrap_or(&0) > 967 { let mut v = map.entry("c").or_insert(0); *v -= 57; }
if *map.get("fy").unwrap_or(&0) > 4440 { let mut v = map.entry("e").or_insert(0); *v += 318; }
if *map.get("pp").unwrap_or(&0) != 102 { let mut v = map.entry("jyi").or_insert(0); *v -= -93; }
if *map.get("xbp").unwrap_or(&0) < 34 { let mut v = map.entry("jyi").or_insert(0); *v += 71; }
if *map.get("xbp").unwrap_or(&0) <= 42 { let mut v = map.entry("pp").or_insert(0); *v += 598; }
if *map.get("wnh").unwrap_or(&0) == -832 { let mut v = map.entry("az").or_insert(0); *v += 143; }
if *map.get("baj").unwrap_or(&0) > -2227 { let mut v = map.entry("xml").or_insert(0); *v -= 13; }
if *map.get("az").unwrap_or(&0) >= 1200 { let mut v = map.entry("ugc").or_insert(0); *v += -643; }

    println!("biggest {:?}", map.values().map(|x| *x).max());
    Ok(())

}